/* iRepair Core · Build 37
   Customer-side Uber-style live journey. Exact technician GPS never reaches this browser. */
(function(){
'use strict';
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/trip-api';
const KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const trips=new Map(),loading=new Set();
let timer=null,scheduled=false;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function getTrip(id){if(!id||loading.has(id))return;loading.add(id);try{const r=await fetch(API+'/jobs/'+encodeURIComponent(id)+'/public',{headers:{Accept:'application/json',Authorization:'Bearer '+KEY,apikey:KEY}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(r.ok)trips.set(id,d.trip||null)}catch(e){}finally{loading.delete(id);schedule()}}
function relevant(){return DB.listJobs().filter(j=>j&&j.id&&['on_my_way','arrived'].includes(j.status)&&j.source==='customer-app')}
function eta(t){if(!t||t.etaMinutes==null)return 'ETA updating';return t.etaMinutes<=1?'Arriving shortly':t.etaMinutes+' min'}
function distance(t){return t&&t.distanceRemainingMiles!=null?Number(t.distanceRemainingMiles).toFixed(1)+' miles away':''}
function mapUrl(loc){const lat=Number(loc.latitude),lng=Number(loc.longitude),dy=.008,dx=.014;const bbox=[lng-dx,lat-dy,lng+dx,lat+dy].map(n=>n.toFixed(5)).join('%2C');return 'https://www.openstreetmap.org/export/embed.html?bbox='+bbox+'&layer=mapnik'}
function markup(job,t){if(job.status==='arrived'||t&&t.state==='arrived')return '<div class="c37-arrived"><strong>📍 Simon has arrived</strong><span>Your technician has reached the repair location.</span></div>';if(job.status!=='on_my_way')return '';if(!t||!t.live||!t.approxLocation)return '<div class="c37-wait"><div class="c37-radar"><i></i></div><div><strong>Simon is on the way</strong><span>Live location is connecting…</span></div></div>';const l=t.approxLocation,head=Number.isFinite(Number(t.headingDegrees))?' style="transform:rotate('+Number(t.headingDegrees)+'deg)"':'';return '<div class="c37-map"><iframe title="Approximate technician location" loading="eager" src="'+mapUrl(l)+'"></iframe><div class="c37-fade top"></div><div class="c37-live"><span><i></i> LIVE</span><strong>'+esc(eta(t))+'</strong><small>'+esc(distance(t)||'Heading to you')+'</small></div><div class="c37-van"'+head+'>🚐</div><div class="c37-fade bottom"></div><div class="c37-caption"><b>Simon is on the way</b><span>Approximate position · exact GPS hidden</span></div></div><div class="c37-stats"><div><small>ETA</small><strong>'+esc(eta(t))+'</strong></div><div><small>DISTANCE</small><strong>'+esc(distance(t)||'Updating')+'</strong></div></div>'}
function render(){scheduled=false;const wanted=new Set();relevant().forEach(job=>{wanted.add(job.id);const box=document.querySelector('[data-jobbox="'+CSS.escape(job.id)+'"]');if(!box)return;let el=box.querySelector('.customer37-trip');if(!el){el=document.createElement('div');el.className='customer37-trip';const firstTip=box.querySelector('.tip');if(firstTip)firstTip.insertAdjacentElement('beforebegin',el);else box.appendChild(el)}const html=markup(job,trips.get(job.id)||null);if(el.innerHTML!==html)el.innerHTML=html});document.querySelectorAll('.customer37-trip').forEach(el=>{const box=el.closest('[data-jobbox]'),id=box&&box.getAttribute('data-jobbox');if(!id||!wanted.has(id))el.remove()})}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(render)}
function refresh(){relevant().forEach(j=>getTrip(j.id));schedule()}
const style=document.createElement('style');style.id='irepair-build37-style';style.textContent=`
.customer37-trip{margin:10px 0 8px;border-radius:18px;overflow:hidden;background:linear-gradient(145deg,#eff9ff,#d9efff);border:1px solid #8bc7ef;box-shadow:0 8px 22px #1b72ad1c}.c37-map{position:relative;height:255px;overflow:hidden;background:#dceaf2}.c37-map iframe{width:100%;height:100%;border:0;filter:saturate(.86) contrast(.94)}.c37-fade{position:absolute;z-index:2;left:0;right:0;pointer-events:none}.c37-fade.top{top:0;height:86px;background:linear-gradient(#08233ba8,transparent)}.c37-fade.bottom{bottom:0;height:86px;background:linear-gradient(transparent,#08233bc9)}.c37-live{position:absolute;z-index:4;left:11px;top:10px;display:grid;grid-template-columns:auto auto;gap:0 8px;align-items:center;padding:8px 10px;border-radius:14px;background:#09243bd9;border:1px solid #b6e4ff77;color:white;backdrop-filter:blur(15px);box-shadow:0 7px 20px #001d3350}.c37-live>span{grid-row:1/3;font-size:8px;font-weight:900;letter-spacing:.08em;color:#bde7ff}.c37-live>span i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:4px;background:#58f27f;box-shadow:0 0 9px #58f27f}.c37-live strong{font-size:19px;line-height:1}.c37-live small{font-size:8px;color:#b7d4e7;margin-top:3px}.c37-van{position:absolute;z-index:5;left:50%;top:52%;width:50px;height:50px;margin:-25px;border-radius:50%;display:grid;place-items:center;background:#0874e7;color:white;border:3px solid white;font-size:23px;box-shadow:0 0 0 10px #1590ff29,0 10px 25px #001d3a70;transition:transform .45s ease}.c37-caption{position:absolute;z-index:4;left:11px;right:11px;bottom:10px;display:flex;justify-content:space-between;align-items:end;gap:8px;color:white}.c37-caption b{font-size:11px}.c37-caption span{font-size:8px;color:#c0d9e9;text-align:right}.c37-stats{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:9px}.c37-stats div{padding:8px 9px;border-radius:11px;background:#fff;border:1px solid #c8e2f5}.c37-stats small{display:block;font-size:7px;font-weight:900;letter-spacing:.06em;color:#6d91ab}.c37-stats strong{display:block;margin-top:2px;font-size:11px;color:#17496e}.c37-wait{display:flex;align-items:center;gap:14px;padding:16px;background:linear-gradient(135deg,#eaf7ff,#d7eeff);color:#17496e}.c37-wait strong,.c37-arrived strong{display:block;font-size:13px}.c37-wait span,.c37-arrived span{display:block;margin-top:3px;font-size:9px;color:#688ba5}.c37-radar{position:relative;flex:0 0 43px;width:43px;height:43px;border:1px solid #2692db;border-radius:50%;box-shadow:0 0 0 9px #2692db12}.c37-radar i{position:absolute;left:50%;top:50%;width:9px;height:9px;margin:-4.5px;border-radius:50%;background:#24b868;box-shadow:0 0 10px #24b868}.c37-arrived{padding:15px;background:linear-gradient(135deg,#e9f9ef,#d2f0de);border:1px solid #8bcea5;color:#24643f}.c37-arrived span{color:#568469}@media(max-width:390px){.c37-map{height:225px}.c37-caption{flex-direction:column;align-items:start}.c37-caption span{text-align:left}}
`;document.head.appendChild(style);
DB.subscribe(refresh);DB.subscribeConnection(refresh);new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});refresh();timer=setInterval(()=>{if(document.visibilityState!=='hidden')refresh()},5000);
})();