/* Build 23 · customer Core + referrals + Repair Relay */
(function(){
  if(!window.IRepairDB)return;
  const REVIEW_URL='https://g.page/r/CRRiPE6ivavxEB0/review';
  const GROWTH_API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/growth-api';
  const API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc3d5bGppaHVmeXhpaWVxeml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0OTc5MTgsImV4cCI6MjEwNjA3MzkxOH0.LdUk-Qf7eielTK8iu0PpbCHNRi9sm6QO7PyPQ7j-zEU';
  let referralBanner='';
  function esc16(s){return String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  async function growth(path,options){const o=Object.assign({method:'GET',headers:{}},options||{});o.headers=Object.assign({'Accept':'application/json','Authorization':'Bearer '+API_KEY,'apikey':API_KEY},o.headers||{});if(o.body&&typeof o.body!=='string'){o.headers['Content-Type']='application/json';o.body=JSON.stringify(o.body)}const r=await fetch(GROWTH_API+path,o);const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){d={raw:t}}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
  async function nativeShare(title,text,url){if(navigator.share){await navigator.share({title,text,url});return true}const value=(text?text+'\n\n':'')+url;try{await navigator.clipboard.writeText(value);try{toast('Link copied — ready to send.')}catch(e){}return true}catch(e){window.prompt('Copy this link',url);return false}}
  function messageHtml16(s){const text=String(s||'');if(!text.includes(REVIEW_URL))return esc16(text);const before=text.split(REVIEW_URL)[0].trim();return esc16(before)+'<br><a href="'+REVIEW_URL+'" target="_blank" rel="noopener" style="display:inline-block;margin-top:10px;padding:10px 14px;border-radius:12px;background:#1474d4;color:white;text-decoration:none;font-weight:800">Leave a Google review →</a>'}
  function jobs16(){return IRepairDB.listJobs().filter(j=>j.source==='customer-app').slice(0,3)}
  function statusClass16(s){return ['completed','cancelled'].includes(s)?s:'active'}
  function coreState16(){const c=IRepairDB.connection||{};return c.online?'<div class="tip" style="margin-bottom:10px"><strong>iRepair Core connected ✓</strong><br>Your repair can sync with the technician app across devices.</div>':'<div class="tip" style="margin-bottom:10px"><strong>Connecting to iRepair Core…</strong><br>The app is using its local cache and will retry automatically.</div>'}
  function referralBanner16(){return referralBanner?'<div class="tip" style="margin-bottom:10px;border:1px solid #9bc6ed;background:#eef8ff"><strong>Recommended by a friend 💙</strong><br>'+esc16(referralBanner)+'</div>':''}
  function sharePanel16(){return '<div class="tip" style="margin:10px 0;background:#eef8ff"><strong>Know someone who needs help with their phone?</strong><br>Send them iRepair in one tap. Their link is tracked as a customer recommendation, but sharing it does not subscribe them to marketing.<button class="btn" style="width:100%;margin-top:9px" data-db16="shareapp">Share iRepair with a friend</button></div>'}
  function customerTimeline(j){const ev=(j.timeline||[]).filter(e=>e.visibility!=='internal').slice().reverse().slice(0,4);if(!ev.length)return '';return '<div style="margin-top:10px">'+ev.map(e=>'<div class="line-meta" style="padding:5px 0;border-top:1px solid #dceaf7"><strong>'+messageHtml16(e.label)+'</strong><br>'+new Date(e.at).toLocaleString('en-GB')+'</div>').join('')+'</div>'}
  function observations16(j){const a=(j.observations||[]).filter(o=>o.customerVisible);if(!a.length)return '';return '<div class="tip" style="margin-top:10px"><strong>Technician observations</strong>'+a.map(o=>'<div style="padding-top:7px;margin-top:7px;border-top:1px solid #d7e6f4"><b>'+esc16(IRepairDB.observationLabel?IRepairDB.observationLabel(o.category):o.category)+'</b><br>'+esc16(o.note)+(o.customerAdvised?'<br><span class="line-meta">Customer advised ✓</span>':'')+'</div>').join('')+'</div>'}
  function chat16(j){const a=(j.messages||[]).slice(-8);return '<div style="margin-top:12px"><strong style="font-size:13px">Repair chat</strong><div style="margin-top:7px;padding:8px;border:1px solid #d6e6f5;border-radius:14px;background:#f7fbff">'+(a.length?a.map(m=>'<div style="margin:6px 0;padding:8px 10px;border-radius:12px;background:'+(m.senderRole==='technician'?'#d9edff':'#eef3f7')+'"><b>'+esc16(m.senderName||m.senderRole)+'</b><br>'+esc16(m.body)+'<div class="line-meta">'+new Date(m.at).toLocaleString('en-GB')+'</div></div>').join(''):'<div class="line-meta">No messages yet.</div>')+'</div><textarea class="input" data-chatinput style="width:100%;min-height:64px;margin-top:7px" placeholder="Reply to iRepair…"></textarea><button class="btn" style="width:100%;margin-top:7px" data-db16="sendchat" data-job="'+esc16(j.id)+'">Send message</button><div class="tip" style="margin-top:7px;font-size:11px"><strong>Passcodes:</strong> please don’t put a device passcode in ordinary chat. Secure passcode sharing will be added when customer accounts are authenticated.</div></div>'}
  function contacts16(j){const c=j.contacts||[],relayReady=c.length>0;return '<div style="margin-top:12px"><strong style="font-size:13px">Secondary repair contact</strong>'+(c.length?c.map(x=>'<div class="tip" style="margin-top:7px"><b>'+esc16(x.fullName)+'</b><br>'+esc16(x.relationship||'Secondary contact')+(x.phone?' · '+esc16(x.phone):'')+(x.receivesUpdates?'<br><span class="line-meta">Receives repair updates</span>':'')+'</div>').join(''):'<div class="line-meta" style="margin-top:5px">Add a friend or family member if they should receive repair updates or handle collection.</div>')+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px"><input class="input" data-contact-name placeholder="Name"><input class="input" data-contact-relation placeholder="Friend / partner…"><input class="input" data-contact-phone placeholder="Mobile"><input class="input" data-contact-email placeholder="Email (optional)"></div><label style="display:flex;align-items:center;gap:7px;margin-top:7px;font-size:11px"><input type="checkbox" data-contact-updates checked> Send repair updates to this person</label><button class="btn secondary" style="width:100%;margin-top:7px" data-db16="addcontact" data-job="'+esc16(j.id)+'">Add secondary contact</button>'+(relayReady?'<button class="btn" style="width:100%;margin-top:7px" data-db16="relay" data-job="'+esc16(j.id)+'">Share Repair Relay with '+esc16(c[c.length-1].fullName)+'</button>':'<div class="tip" style="margin-top:7px"><strong>Repair Relay</strong><br>Once a secondary contact is added, one tap creates a temporary mini-app link so they can see repair progress and message iRepair while your phone is unavailable.</div>')+'<div class="line-meta" style="margin-top:6px">A secondary contact is part of this repair only. They are not automatically added to marketing; their own iRepair account can be offered separately after the repair.</div></div>'}
  function jobCard16(j){return '<div class="line" data-jobbox="'+esc16(j.id)+'"><div class="flexbetween"><strong>'+esc16(j.device)+'</strong><span class="pill '+statusClass16(j.status)+'">'+esc16(IRepairDB.label(j.status))+'</span></div><div class="line-meta">'+esc16(j.repair)+' · '+esc16(j.service)+(j.postcode?' · '+esc16(j.postcode):'')+'</div><div class="line-meta">Reference '+esc16(j.id)+' · '+esc16(IRepairDB.paymentLabel?IRepairDB.paymentLabel(j.paymentState):j.paymentState)+'</div>'+(j.customerMessage?'<div class="tip" style="margin-top:9px"><strong>Update from iRepair:</strong><br>'+messageHtml16(j.customerMessage)+'</div>':'')+observations16(j)+chat16(j)+contacts16(j)+customerTimeline(j)+'</div>'}
  function customerSyncCard16(){const jobs=jobs16();return '<section class="glass panel" id="prototypeSync16"><div class="eyebrow">PROTOTYPE · CUSTOMER ↔ iREPAIR CORE ↔ TECHNICIAN</div><h2>Your repair connection</h2><p class="muted">This customer view only refreshes repair references already known to this device. Technician-only notes and other customers’ jobs are not shown here.</p>'+referralBanner16()+coreState16()+sharePanel16()+(jobs.length?'<div>'+jobs.map(jobCard16).join('')+'</div>':'<div class="tip">No prototype booking is saved on this device yet. Create one below, then open the technician app on this or another device.</div>')+'<div class="button-row"><button class="btn" data-db16="create">Create demo booking</button><button class="btn secondary" data-db16="tech">Open technician app</button></div><button class="btn ghost" data-db16="refresh">Sync with Core ↻</button></section>'}
  const oldHome16=homeScreen;homeScreen=function(){return oldHome16()+customerSyncCard16()};
  async function createReferral16(){try{const d=await growth('/referrals',{method:'POST',body:{channel:'native-share',sourceContext:'customer-app'}});await nativeShare('iRepair','If you ever need help with your phone, I recommend iRepair.',d.shareUrl);try{toast('iRepair referral link ready to share.')}catch(e){}}catch(e){try{toast('Could not create the share link yet.')}catch(x){}}}
  async function createRelay16(id){const job=IRepairDB.getJob(id),contacts=(job&&job.contacts)||[];if(!job||!contacts.length){try{toast('Add a secondary contact first.')}catch(e){}return}const c=contacts[contacts.length-1];try{const d=await growth('/relay',{method:'POST',body:{repairId:id,contactId:c.id,displayName:c.fullName,phone:c.phone,email:c.email}});await nativeShare('iRepair Repair Relay','This temporary iRepair link lets you follow the repair and message Simon while the phone is being repaired.',d.relayUrl);try{toast('Repair Relay ready to send to '+c.fullName+'.')}catch(e){}}catch(e){try{toast('Could not create Repair Relay yet.')}catch(x){}}}
  document.addEventListener('click',function(e){const b=e.target.closest('button');if(!b||!b.dataset.db16)return;const a=b.dataset.db16;
    if(a==='shareapp'){createReferral16();return}
    if(a==='create'){const job=IRepairDB.createDemoBooking();try{toast('Demo booking '+job.id+' created and queued for iRepair Core.')}catch(err){}render();return}
    if(a==='tech'){window.open('/tech.html','_blank');return}
    if(a==='refresh'){IRepairDB.syncRemote().then(function(){try{render()}catch(e){}});return}
    const id=b.dataset.job,box=b.closest('[data-jobbox]');if(!id||!box)return;
    if(a==='relay'){createRelay16(id);return}
    if(a==='sendchat'){const t=box.querySelector('[data-chatinput]');if(t&&t.value.trim()){IRepairDB.sendMessage(id,t.value,'customer','Customer','chat','customer');try{toast('Message sent to iRepair.')}catch(err){}render()}return}
    if(a==='addcontact'){const n=box.querySelector('[data-contact-name]');if(n&&n.value.trim()){IRepairDB.addSecondaryContact(id,{fullName:n.value,relationship:(box.querySelector('[data-contact-relation]')||{}).value||'',phone:(box.querySelector('[data-contact-phone]')||{}).value||'',email:(box.querySelector('[data-contact-email]')||{}).value||'',receivesUpdates:!!(box.querySelector('[data-contact-updates]')||{}).checked},'customer');try{toast('Secondary repair contact added.')}catch(err){}render()}return}
  },false);
  (async function referralOpen(){try{const q=new URLSearchParams(window.parent&&window.parent.location?window.parent.location.search:location.search),code=q.get('ref');if(!code)return;const d=await growth('/referrals/'+encodeURIComponent(code));referralBanner=d.referral&&d.referral.inviterName?d.referral.inviterName+' recommended iRepair to you.':'Someone you know recommended iRepair to you.';if(typeof mode!=='undefined'&&mode==='home')render()}catch(e){}})();
  IRepairDB.subscribe(function(){if(typeof mode!=='undefined'&&mode==='home'){try{render()}catch(e){}}});if(IRepairDB.subscribeConnection)IRepairDB.subscribeConnection(function(){if(typeof mode!=='undefined'&&mode==='home'){try{render()}catch(e){}}});
})();
