/* Build 13 · guided Device Scanner prototype */
var scan13={screen:'start',target:'',step:0,shots:{front:null,back:null,bottom:null},stream:null,error:'',busy:false};
const SCAN13_STEPS=[
 {key:'front',title:'Show me the front of the device',sub:'Remove the case if it covers the screen edges. Keep the whole device inside the guide.',guide:'front',label:'Front of device'},
 {key:'back',title:'Now show me the back',sub:'Keep the cameras, edges and any writing visible. Remove the case if it hides the camera area.',guide:'back',label:'Back of device'},
 {key:'bottom',title:'Show me where the charger plugs in',sub:'Hold the bottom edge close enough that the charging socket and nearby openings are clear.',guide:'edge',label:'Charging edge'}
];
function scan13Reset(){scan13StopCamera();scan13={screen:'start',target:'',step:0,shots:{front:null,back:null,bottom:null},stream:null,error:'',busy:false}}
function scan13Platform(){const u=navigator.userAgent||'';if(/Android/i.test(u))return 'Android';if(/iPhone|iPad|iPod/i.test(u))return 'Apple';return 'Unknown'}
function scan13StopCamera(){try{scan13.stream?.getTracks?.().forEach(t=>t.stop())}catch(e){}scan13.stream=null}
function scan13Steps(){return '<div class="scan13-steps">'+SCAN13_STEPS.map((x,i)=>'<span class="scan13-step '+(i<scan13.step?'done':i===scan13.step?'current':'')+'"></span>').join('')+'</div>'}
function scan13Shots(){return '<div class="scan13-shot-grid">'+SCAN13_STEPS.map(s=>'<div class="scan13-shot">'+(scan13.shots[s.key]?'<img src="'+scan13.shots[s.key]+'" alt="'+safe(s.label)+'">':'<div class="placeholder">＋</div>')+'<small>'+safe(s.label)+'</small></div>').join('')+'</div>'}
function scan13StartView(){return '<section class="glass panel"><div class="eyebrow">DEVICE SCANNER · PROTOTYPE</div><h1 style="margin-left:0">Identify a device</h1><p class="muted">iRepair will collect the evidence it needs instead of asking you to know the model.</p><div class="scan13-choice">'+'<button class="scan13-card" data-scan13-target="this"><span class="ico">📱</span><span><strong>Identify this device</strong><small>The phone or tablet you are using right now.</small></span></button>'+'<button class="scan13-card" data-scan13-target="another"><span class="ico">⌁</span><span><strong>Identify another device</strong><small>Use this camera to scan a phone, iPad or tablet in front of you.</small></span></button>'+'</div><button class="btn ghost" data-scan13-action="home">← Back to home</button></section>'}
function scan13ThisDeviceView(){const os=scan13Platform();let copy=os==='Android'?'A future native Android build can read the manufacturer and model directly from the operating system. The web prototype cannot safely access that exact hardware value.':os==='Apple'?'iOS does not expose the retail iPhone/iPad model name to this web prototype. The native app can use permitted device information and fall back to Settings → General → About when needed.':'The web prototype cannot safely read an exact retail hardware model from this device.';return '<section class="glass panel"><div class="eyebrow">IDENTIFY THIS DEVICE</div><h2>Use the device itself where possible</h2><div class="scan13-native"><div class="os">Detected platform: '+safe(os)+'</div><p>'+safe(copy)+'</p></div><div class="tip"><strong>Production behaviour:</strong> iRepair first asks the operating system for any reliable model information it is allowed to read. If that is not enough, it asks for one exact Settings/About check rather than guessing.</div>'+(os==='Apple'?'<button class="btn" data-scan13-action="apple-settings">Use Settings → General → About →</button>':'<button class="btn" data-scan13-action="another">Scan another device with the camera →</button>')+'<button class="btn ghost" data-scan13-action="back">← Back</button></section>'}
function scan13CameraView(){const s=SCAN13_STEPS[scan13.step];return '<section class="glass panel scan13-stage">'+scan13Steps()+'<div class="eyebrow">GUIDED SCAN</div><h2>'+safe(s.title)+'</h2><p class="scan13-instruction">'+safe(s.sub)+'</p>'+scan13Shots()+'<div class="scan13-camera"><video id="scan13Video" autoplay playsinline muted></video><div class="scan13-guide '+safe(s.guide)+'"></div><div class="scan13-guide-label">'+safe(s.label)+'</div></div>'+(scan13.error?'<div class="warning">'+safe(scan13.error)+'</div>':'')+'<button class="scan13-capture" aria-label="Take photo" data-scan13-action="capture"></button><p class="muted" style="text-align:center;margin-top:6px">Tap the white button when the device is clear.</p><div class="scan13-privacy">For this prototype, captured pictures stay in this browser session and are not uploaded anywhere. The recognition backend will be connected separately.</div><button class="btn secondary" data-scan13-action="file">Choose a photo instead</button><input id="scan13File" type="file" accept="image/*" capture="environment" hidden><button class="btn ghost" data-scan13-action="back">← Cancel scan</button></section>'}
function scan13ReviewView(){const s=SCAN13_STEPS[scan13.step];const src=scan13.shots[s.key];return '<section class="glass panel scan13-stage">'+scan13Steps()+'<div class="eyebrow">CHECK PHOTO</div><h2>'+safe(s.label)+'</h2><p class="scan13-instruction">Make sure the whole area iRepair asked for is visible and reasonably sharp.</p><div class="scan13-camera"><img src="'+src+'" alt="Captured '+safe(s.label)+'"><div class="scan13-guide '+safe(s.guide)+'"></div></div><button class="btn" data-scan13-action="use-photo">Use this photo →</button><button class="btn secondary" data-scan13-action="retake">Retake</button><button class="btn ghost" data-scan13-action="back">← Cancel scan</button></section>'}
function scan13CompleteView(){return '<section class="glass panel scan13-stage"><div class="eyebrow">SCAN CAPTURED</div><h2>That is the evidence set</h2>'+scan13Shots()+'<div class="scan13-status"><strong>Next layer: AI identification</strong><p>The live prototype can now collect the correct photographs. The recognition service is the next development layer: it will inspect these views, compare observations with the device catalogue, and either confirm the model or request one more targeted photo/detail.</p></div><div class="tip"><strong>Safety rule:</strong> a “likely” match will never be allowed to reserve a model-specific part. If the evidence is ambiguous, iRepair asks for more evidence or a model number.</div><button class="btn" data-scan13-action="existing-id">Use the existing iPhone identifier as fallback →</button><button class="btn secondary" data-scan13-action="restart">Scan another device</button><button class="btn ghost" data-scan13-action="home">← Back to home</button></section>'}
function scan13View(){if(scan13.screen==='this')return scan13ThisDeviceView();if(scan13.screen==='camera')return scan13CameraView();if(scan13.screen==='review')return scan13ReviewView();if(scan13.screen==='complete')return scan13CompleteView();return scan13StartView()}
const _homeScreen13=homeScreen;
homeScreen=function(){return '<section class="scan13-hero"><div class="scan13-hero-row"><div class="scan13-hero-icon">⌁</div><div><div class="eyebrow">NEW · DEVICE IDENTITY</div><h2>Scan a device</h2><p>Not sure what phone or tablet it is? Let iRepair collect the evidence needed to identify it.</p></div></div><button class="btn" data-action="device-scanner">Scan / identify a device →</button></section>'+_homeScreen13()}
const _render13=render;
render=function(){if(mode==='scanner'){document.querySelector('#main').innerHTML=scan13View();setNav('Home');setTimeout(scan13AfterRender,0);return}_render13()}
async function scan13AfterRender(){if(scan13.screen!=='camera')return;const video=document.getElementById('scan13Video');if(!video)return;scan13.error='';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is not available in this browser.');scan13.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=scan13.stream;await video.play().catch(()=>{});}catch(err){scan13.error='I could not open the camera. You can choose a photo from your library instead.';scan13StopCamera();render();}}
function scan13OpenCamera(){scan13StopCamera();scan13.screen='camera';scan13.error='';render()}
function scan13Capture(){const v=document.getElementById('scan13Video');if(!v||!v.videoWidth){scan13.error='The camera is not ready yet. Try again in a moment, or choose a photo instead.';render();return}const max=1400,scale=Math.min(1,max/v.videoWidth);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);const key=SCAN13_STEPS[scan13.step].key;scan13.shots[key]=c.toDataURL('image/jpeg',0.86);scan13StopCamera();scan13.screen='review';render()}
function scan13UsePhoto(){if(scan13.step<SCAN13_STEPS.length-1){scan13.step++;scan13OpenCamera()}else{scan13StopCamera();scan13.screen='complete';render()}}
function scan13FilePick(){document.getElementById('scan13File')?.click()}
function scan13HandleFile(file){if(!file)return;const r=new FileReader();r.onload=function(){scan13StopCamera();scan13.shots[SCAN13_STEPS[scan13.step].key]=String(r.result||'');scan13.screen='review';render()};r.readAsDataURL(file)}
document.addEventListener('click',function(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='device-scanner'){scan13Reset();mode='scanner';render();window.scrollTo({top:0,behavior:'instant'});return}if(b.dataset.scan13Target){scan13.target=b.dataset.scan13Target;scan13.screen=b.dataset.scan13Target==='this'?'this':'camera';scan13.step=0;mode='scanner';render();return}const a=b.dataset.scan13Action;if(!a)return;if(a==='home'){scan13Reset();mode='home';render();return}if(a==='back'){scan13Reset();mode='scanner';render();return}if(a==='another'){scan13.target='another';scan13.screen='camera';scan13.step=0;render();return}if(a==='capture'){scan13Capture();return}if(a==='file'){scan13FilePick();return}if(a==='retake'){scan13.shots[SCAN13_STEPS[scan13.step].key]=null;scan13OpenCamera();return}if(a==='use-photo'){scan13UsePhoto();return}if(a==='restart'){scan13Reset();mode='scanner';render();return}if(a==='existing-id'){scan13StopCamera();helpReset();helpBrand='Apple iPhone';if(typeof id12Reset==='function')id12Reset();mode='help';render();return}if(a==='apple-settings'){scan13StopCamera();helpReset();helpBrand='Apple iPhone';if(typeof id12Reset==='function'){id12Reset();id12.screen='settings'}mode='help';render();return}},false);
document.addEventListener('change',function(e){if(e.target?.id==='scan13File')scan13HandleFile(e.target.files?.[0])},false);
