/* iRepair Core · Build 36
   Customer Satellite matching with server-side route intelligence.
   Technician/customer coordinates are never rendered back to the customer. */
(function(){
'use strict';
if(typeof homeScreen!=='function')return;
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/satellite-api';
const API_KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const CTX_KEY='irepair_satellite_context_v1';
let satellite=null,match=null,loading=false,error='';
const previousHome=homeScreen;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,options){const o=Object.assign({method:'GET',headers:{}},options||{});o.headers=Object.assign({'Accept':'application/json','Authorization':'Bearer '+API_KEY,'apikey':API_KEY},o.headers||{});if(o.body&&typeof o.body!=='string'){o.headers['Content-Type']='application/json';o.body=JSON.stringify(o.body)}const r=await fetch(API+path,o),text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(e){}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function rerender(){try{if(typeof mode!=='undefined'&&mode==='home')render()}catch(e){}}
function readContext(){try{const raw=sessionStorage.getItem(CTX_KEY);if(!raw)return null;const ctx=JSON.parse(raw),exp=new Date(ctx.expiresAt||0).getTime();if(!ctx||!ctx.claimToken||!Number.isFinite(exp)||exp<=Date.now()){sessionStorage.removeItem(CTX_KEY);return null}return ctx}catch(e){return null}}
function saveContext(type,token,expiresAt){if(!token)return null;const fallback=Date.now()+90*60000,serverExp=new Date(expiresAt||0).getTime();const ctx={type,mode:satellite&&satellite.mode||'',claimToken:String(token),matchedAt:new Date().toISOString(),expiresAt:new Date(Number.isFinite(serverExp)&&serverExp>Date.now()?serverExp:fallback).toISOString()};try{sessionStorage.setItem(CTX_KEY,JSON.stringify(ctx))}catch(e){}window.IRepairSatelliteContext=ctx;return ctx}
function clearContext(){try{sessionStorage.removeItem(CTX_KEY)}catch(e){}window.IRepairSatelliteContext=null}
async function loadStatus(){try{const d=await api('/status');satellite=d.satellite||null;error='';rerender()}catch(e){satellite=null;error=''}}
function routeNote(){if(!match||!match.match)return '';const r=match.route||{},info=match.routing||{};if(info.provider==='google_routes'){const bits=[];if(Number.isFinite(Number(r.approachMinutes)))bits.push('about '+r.approachMinutes+' min drive');if(Number.isFinite(Number(r.extraDriveMinutes)))bits.push('+'+r.extraDriveMinutes+' min route detour');return bits.length?' Traffic-aware check: '+bits.join(' · ')+'.':''}return ''}
function card(){
 if(!satellite||!satellite.active)return '';
 if(satellite.officeCallIn)return '<div class="b36-sat office"><div class="b36-orbit">⌾</div><div class="b36-copy"><span>LIVE AVAILABILITY</span><strong>Killay call-in available</strong><small>A technician has repair capacity at '+esc(satellite.officeLabel||'the Killay office')+' today.</small></div><button class="b36-action" data-s36-start="office">Check repair options</button></div>';
 if(!satellite.canCheckNearby)return '';
 if(match&&match.match)return '<div class="b36-sat matched"><div class="b36-orbit">⌾</div><div class="b36-copy"><span>SATELLITE MATCH</span><strong>'+esc(match.headline||'Technician nearby today')+'</strong><small>'+esc(match.message||'Fast local repair availability may be possible.')+esc(routeNote())+'</small></div><button class="b36-action" data-s36-start="mobile">Use this availability</button></div>';
 if(match&&match.match===false)return '<div class="b36-sat no-match"><div class="b36-orbit">⌾</div><div class="b36-copy"><span>TECHNICIAN WORKING LOCALLY</span><strong>No fast-route match right now</strong><small>'+esc(match.message||'Normal booking is still available.')+'</small></div><button class="b36-action secondary" data-s36-normal>Book normally</button></div>';
 return '<div class="b36-sat"><div class="b36-orbit">⌾</div><div class="b36-copy"><span>SATELLITE · LIVE</span><strong>Technician working locally today</strong><small>Share your location once to check whether your repair fits around the current route. Your precise location is used for this check only.</small></div><button class="b36-action" data-s36-check '+(loading?'disabled':'')+'>'+(loading?'Checking…':'Check near me')+'</button>'+(error?'<div class="b36-error">'+esc(error)+'</div>':'')+'</div>';
}
homeScreen=function(){const html=previousHome();if(!html.includes('b27-home'))return html;const c=card();return c?html.replace('<div class="route-choice">',c+'<div class="route-choice">'):html};
async function checkNearby(){if(loading)return;if(!navigator.geolocation){error='Location checking is not supported on this device.';rerender();return}loading=true;match=null;error='';rerender();navigator.geolocation.getCurrentPosition(async p=>{try{const d=await api('/match',{method:'POST',body:{latitude:p.coords.latitude,longitude:p.coords.longitude}});satellite=d.satellite||satellite;match=d;error=''}catch(e){error='I could not check local availability just now. Normal booking is still available.'}finally{loading=false;rerender()}},()=>{loading=false;error='Location was not shared. You can still use normal booking.';rerender()},{enableHighAccuracy:false,timeout:9000,maximumAge:120000})}
async function begin(type){let token='',expiresAt='';if(type==='office'){try{const d=await api('/office-claim',{method:'POST'});token=String(d.claimToken||'');expiresAt=String(d.claimExpiresAt||'')}catch(e){error='Office availability changed before the repair was started. Please check again.';loadStatus();return}}else if(type==='mobile'&&match){token=String(match.claimToken||'');expiresAt=String(match.claimExpiresAt||'')}if(token)saveContext(type,token,expiresAt);else clearContext();try{mode='book';stage=1;fault='';variant='';editId=null;if(typeof resetDiagnostic==='function')resetDiagnostic();const d=typeof selected==='function'?selected():null;if(d&&typeof basket!=='undefined'&&!basket.some(r=>r.deviceId===d.id)){d.model='';d.custom=''}render();window.scrollTo({top:0,behavior:'instant'})}catch(e){location.reload()}}
async function claimJob(jobRef,ctx,attempt){if(!ctx||!ctx.claimToken||!jobRef)return;try{await api('/claim',{method:'POST',body:{jobRef,claimToken:ctx.claimToken}})}catch(e){if((attempt||0)<3)setTimeout(()=>claimJob(jobRef,ctx,(attempt||0)+1),[800,1600,3000,5000][attempt||0])}}
function hookBooking(){const db=window.IRepairDB;if(!db||typeof db.createJob!=='function'||db.createJob.__satellite36)return;const original=db.createJob;const wrapped=function(input,source){const job=original.call(db,input,source),ctx=readContext();if(job&&ctx&&['office','mobile'].includes(ctx.type))setTimeout(()=>claimJob(job.id,ctx,0),350);return job};wrapped.__satellite36=true;db.createJob=wrapped}
window.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-s36-check')){e.preventDefault();e.stopImmediatePropagation();checkNearby();return}if(b.hasAttribute('data-s36-start')){e.preventDefault();e.stopImmediatePropagation();begin(b.dataset.s36Start||'mobile');return}if(b.hasAttribute('data-s36-normal')){e.preventDefault();e.stopImmediatePropagation();clearContext();begin('normal');return}},true);
const style=document.createElement('style');style.id='irepair-build36-style';style.textContent=`
.b36-sat{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:11px;align-items:center;margin:10px 0 12px;padding:12px;border:1px solid rgba(41,144,234,.58);border-radius:19px;background:linear-gradient(135deg,rgba(227,247,255,.90),rgba(183,225,255,.68));box-shadow:inset 0 1px 1px rgba(255,255,255,.95),0 9px 24px rgba(25,101,166,.16);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px)}.b36-sat.office,.b36-sat.matched{border-color:rgba(43,179,113,.65);background:linear-gradient(135deg,rgba(234,255,245,.94),rgba(190,240,215,.74))}.b36-sat.no-match{border-color:rgba(137,171,201,.55);background:linear-gradient(135deg,rgba(245,250,255,.94),rgba(222,235,246,.76))}.b36-orbit{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:rgba(255,255,255,.72);color:#0874e7;font-size:29px;box-shadow:inset 0 1px 0 #fff,0 5px 15px rgba(28,95,153,.12)}.office .b36-orbit,.matched .b36-orbit{color:#138b54}.b36-copy{min-width:0;text-align:left}.b36-copy strong{display:block;font-size:14px;line-height:1.2;color:#143e65}.b36-copy small{display:block;margin-top:3px;font-size:10px;line-height:1.35;color:#58758f}.b36-copy span{display:block;margin-bottom:3px;font-size:8px;font-weight:900;letter-spacing:.09em;color:#0874e7}.office .b36-copy span,.matched .b36-copy span{color:#117a49}.b36-action{border:0;border-radius:12px;background:#0874e7;color:#fff;padding:9px 10px;font-size:9px;font-weight:850;line-height:1.15;max-width:94px;box-shadow:0 5px 13px rgba(8,116,231,.22)}.b36-action:disabled{opacity:.55}.b36-action.secondary{background:#58758f}.office .b36-action,.matched .b36-action{background:#138b54}.b36-error{grid-column:2/-1;font-size:9px;line-height:1.35;color:#8a4f20}@media(max-width:390px){.b36-sat{grid-template-columns:38px minmax(0,1fr);gap:9px}.b36-orbit{width:38px;height:38px;font-size:25px}.b36-action{grid-column:2;width:100%;max-width:none}.b36-copy strong{font-size:13px}}
`;document.head.appendChild(style);const existing=readContext();if(existing)window.IRepairSatelliteContext=existing;hookBooking();loadStatus();
})();