function helpDeviceScreen(){
 let isApple=helpBrand==='Apple iPhone',isOther=helpBrand==='Other phone';
 let found=helpKnown==='yes',unsure=helpKnown==='no';
 return `<section class="glass panel">${helpProgress()}<div class="eyebrow">STEP 1 · YOUR DEVICE</div><h2>What type of phone is it?</h2><div class="phone-type-grid"><button class="phone-type-card" data-help-brand="Apple iPhone" aria-pressed="${isApple}"><span class="phone-type-icon">📱</span><strong>Apple iPhone</strong><small>Use the iPhone visual identifier</small></button><button class="phone-type-card" data-help-brand="Other phone" aria-pressed="${isOther}"><span class="phone-type-icon">📲</span><strong>Other phone</strong><small>We’ll build this route later</small></button></div>${isOther?`<div class="tip"><strong>Other-phone identification is parked for now.</strong> If you know the model, you can enter it manually and continue to the fault questions.</div><label class="field-label" for="helpCustomModel">Phone model (if known)</label><input class="field" id="helpCustomModel" maxlength="90" value="${selected().model==='otherphone'?safe(selected().custom):''}" placeholder="e.g. Samsung Galaxy S23 Ultra"><button class="btn" style="margin-top:12px" data-action="help-other-next">Continue to the problem →</button>`:''}${isApple?`<div class="divider"></div><h2>Do you know the exact iPhone model?</h2><div class="choice-grid"><button class="choice" data-help-known="yes" aria-pressed="${found}">✓ Yes, I know it</button><button class="choice" data-help-known="no" aria-pressed="${unsure}">? I’m not sure</button></div>${found?`<label class="field-label" for="helpModel">Choose exact iPhone</label><select class="field" id="helpModel">${helpModelOptions()}</select><button class="btn" style="margin-top:12px" data-action="help-device-next" ${!IPHONE_KEYS.includes(selected().model)?'disabled':''}>That’s my iPhone →</button>`:''}${unsure?`<label class="field-label">Can the iPhone switch on and open Settings?</label><div class="pill-row">${['Yes','No'].map(v=>`<button class="pill" data-help-usable="${v}" aria-pressed="${helpUsable===v}">${v}</button>`).join('')}</div>${helpUsable==='Yes'?`<div class="tip"><strong>Fastest and most accurate:</strong> open <strong>Settings → General → About</strong> and read <strong>Model Name</strong>.</div><button class="btn" data-action="help-found-model">I found the model name →</button><button class="btn secondary" style="margin-top:8px" data-action="help-visual">I still need to identify it visually →</button>`:''}${helpUsable==='No'||helpUsable==='Visual'?visualIdentifier():''}`:''}`:''}<button class="btn ghost help-back" data-action="help-home">← Back</button></section>`;
}
function helpIssueScreen(){let issueCards=[['screen','▣','Screen / display','Cracked glass, lines, black display or touch problem'],['battery','▤','Battery','Draining quickly, shutting down or battery warning'],['charging','⚡','Charging','Cable connection, slow/no charging or loose-feeling port'],['power','⏻',"Won’t switch on",'No response, boot problem or powers off'],['audio','◖))','Sound','Quiet, muffled, crackling, speaker or microphone'],['camera','◉','Camera','Focus, shaking, black image, lens or camera fault'],['rear','◫','Back glass / cosmetic','Rear glass damage or cosmetic damage'],['liquid','≈','Liquid damage','Water or liquid exposure'],['other','···','Something else','None of these describe it']];return `<section class="glass panel">${helpProgress()}<div class="eyebrow">STEP 2 · WHAT’S HAPPENING?</div><h2>Which sounds closest?</h2><p class="muted">You don’t need to know the repair name. Pick the symptom and we’ll take you to the most likely repair path.</p><div class="route-choice">${issueCards.map(i=>`<button class="route-card ${helpIssue===i[0]?'primary':''}" data-help-issue="${i[0]}"><strong>${i[1]} ${safe(i[2])}</strong><small>${safe(i[3])}</small></button>`).join('')}</div>${helpIssue?`<div class="tip">We’ll open the <strong>${safe(FAULTS.find(f=>f.id===helpIssue)?.label||'diagnostic')}</strong> route next. You can change it or add another problem before booking.</div><button class="btn" data-action="help-show-options">Show me the repair options →</button>`:''}<button class="btn ghost help-back" data-action="help-device-back">← Back to device</button></section>`}
function helpScreen(){return helpStep===1?helpDeviceScreen():helpIssueScreen()}
function makeUnconfirmedModel(){let d=selected();d.model='otherphone';let bits=['Apple iPhone',CAMERA_LAYOUTS.find(x=>x[0]===helpCameras)?.[1]||helpCameras,helpDisplay,helpPort].filter(Boolean);d.custom=('Unconfirmed '+bits.join(' · ')).slice(0,90)}
function openHelpIssue(id){helpIssue=id;render()}
function applyHelpIssue(){if(!helpIssue)return;fault=helpIssue;editId=null;resetDiagnostic();if(helpIssue==='camera')diagnostic.notes='Customer selected camera problem in guided help.';if(helpIssue==='power')diagnostic.notes='Customer selected no-power / won’t-switch-on problem in guided help.';mode='book';stage=1;render();setTimeout(()=>document.getElementById('faultDetail')?.scrollIntoView({block:'start',behavior:'smooth'}),0)}

