/* iRepair Technician · Quick Replies MVP
   Deterministic templates + validated Supabase price cache + local offline cache.
   No AI/LLM calls are made when generating or copying a reply. */
(function(g){
'use strict';
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/quick-replies-api';
const PRICE_KEY='irepair_quick_replies_prices_v1';
const USAGE_KEY='irepair_quick_replies_usage_v1';
let payload=readJson(PRICE_KEY,{version:null,prices:[]});
let usage=readJson(USAGE_KEY,{items:{}});
let query='';
let loading=false;
let notice='';
let noticeType='';
let lastNetworkOk=false;
let manualText='';
let toastTimer=null;
function readJson(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x&&typeof x==='object'?x:fallback}catch(e){return fallback}}
function saveJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function money(n){return '£'+Number(n).toFixed(2).replace('.00','')}
function emit(){try{g.dispatchEvent(new CustomEvent('irepair-quick-replies-change'))}catch(e){}}
function usageFor(id){return usage.items[id]||{count:0,lastUsed:null,favourite:false}}
function setUsage(id,patch){usage.items[id]=Object.assign({},usageFor(id),patch);saveJson(USAGE_KEY,usage)}
function normalText(s){return String(s||'').toLowerCase().replace(/iphone/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function formatDate(iso){if(!iso)return 'Not yet synchronised';try{return new Date(iso).toLocaleString('en-GB',{day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'})}catch(e){return iso}}
function groupedPrices(){const map={};(payload.prices||[]).forEach(p=>{if(!p||p.repair_type!=='screen'||!p.model_key||!p.model||!Number.isFinite(Number(p.price)))return;const k=p.model_key;if(!map[k])map[k]={modelKey:k,model:p.model,deviceFamily:p.device_family||'Apple',repairType:'screen',options:[]};map[k].options.push({key:p.option_key,label:p.option_label,price:Number(p.price)})});return Object.values(map).map(x=>{const order=['HDLCD','OLED','ORIGINAL','SCREEN'];x.options.sort((a,b)=>order.indexOf(a.key)-order.indexOf(b.key));return x})}
function screenMessage(t){const options=t.options||[];if(!options.length)return null;const lines=['Hi 😊 Yes, I can replace the screen on your '+t.model+'.',''];if(options.length===1){const o=options[0];if(o.key==='HDLCD')lines.push('🔧 HDLCD – '+money(o.price),'A good lower-cost option. It gives a clear display, although LCD technology can use a little more battery than the original OLED screen.','','Would you like me to check live stock for you? 😊');else if(o.key==='OLED')lines.push('✨ OLED – '+money(o.price),'Closer to the original display technology, with better blacks, contrast and a smoother, more responsive feel — particularly noticeable if you’re a fast texter.','','Would you like me to check live stock for you? 😊');else if(o.key==='ORIGINAL')lines.push('🍎 Apple Original/Genuine – '+money(o.price),'An original Apple display option is available for this model.','','Would you like me to check live stock for you? 😊');else lines.push('Screen replacement – '+money(o.price),'','Would you like me to check live stock for you? 😊');return lines.join('\n')}lines.push('I have '+(options.length===2?'two':options.length===3?'three':String(options.length))+' screen options available:','');options.forEach((o,i)=>{if(o.key==='HDLCD')lines.push('🔧 HDLCD – '+money(o.price),'A good lower-cost option. It gives a clear display, although LCD technology can use a little more battery than the original OLED screen.');else if(o.key==='OLED')lines.push('✨ OLED – '+money(o.price),'Closer to the original display technology, with better blacks, contrast and a smoother, more responsive feel — particularly noticeable if you’re a fast texter.');else if(o.key==='ORIGINAL')lines.push('🍎 Apple Original/Genuine – '+money(o.price),'An original Apple display option is available for this model.');else lines.push('🔧 '+o.label+' – '+money(o.price));if(i<options.length-1)lines.push('')});lines.push('','Which screen would you prefer? I will check live stock for you 😊');return lines.join('\n')}
function templates(){return groupedPrices().map(gp=>{const id='screen:'+gp.modelKey,u=usageFor(id),msg=screenMessage(gp);return{id,title:gp.model+' Screen',category:'Screen Repairs',deviceFamily:gp.deviceFamily,model:gp.model,modelKey:gp.modelKey,repairType:'screen',templateText:'screen-v1',requiredPricingFields:gp.options.map(o=>o.key),keywords:[gp.model,gp.model.replace(/^iPhone\s*/i,''),'screen','display','lcd','hdlcd','oled'].join(' '),favourite:!!u.favourite,usageCount:Number(u.count||0),lastUsed:u.lastUsed||null,active:!!msg,optionalVariants:[],options:gp.options,message:msg}}).filter(t=>t.active).sort((a,b)=>modelRank(b.model)-modelRank(a.model)||a.model.localeCompare(b.model,undefined,{numeric:true}))}
function modelRank(name){const m=String(name).match(/iPhone\s+(\d+)/i);return m?Number(m[1]):0}
function matches(t,q){if(!q)return true;const n=normalText(q),hay=normalText([t.title,t.model,t.keywords,t.repairType].join(' '));return n.split(/\s+/).every(part=>hay.includes(part))}
function ranked(q){return templates().filter(t=>matches(t,q)).sort((a,b)=>{const ua=usageFor(a.id),ub=usageFor(b.id);if(q)return modelRank(b.model)-modelRank(a.model);return Number(ub.favourite)-Number(ua.favourite)||Number(ub.count||0)-Number(ua.count||0)||String(ub.lastUsed||'').localeCompare(String(ua.lastUsed||''))})}
function recent(){return templates().filter(t=>usageFor(t.id).lastUsed).sort((a,b)=>String(usageFor(b.id).lastUsed).localeCompare(String(usageFor(a.id).lastUsed))).slice(0,4)}
function favourites(){return templates().filter(t=>usageFor(t.id).favourite).sort((a,b)=>Number(usageFor(b.id).count||0)-Number(usageFor(a.id).count||0)).slice(0,6)}
function pricesLabel(t){return t.options.map(o=>o.label+' '+money(o.price)).join(' · ')}
function card(t){const u=usageFor(t.id);return '<div style="position:relative"><button class="qr-card" type="button" data-qr-copy="'+esc(t.id)+'"><strong>'+esc(t.title)+'</strong><small><span class="qr-price">'+esc(pricesLabel(t))+'</span>'+(u.count?' · used '+u.count+'×':'')+'</small></button><button class="qr-star '+(u.favourite?'on':'')+'" type="button" aria-label="'+(u.favourite?'Remove favourite':'Add favourite')+'" data-qr-fav="'+esc(t.id)+'">★</button></div>'}
function cards(list,cls){return '<div class="'+(cls||'qr-list')+'">'+list.map(card).join('')+'</div>'}
function resultsHtml(){const q=query.trim(),all=ranked(q);if(q)return '<div class="qr-section"><h3>Search results</h3><span>'+all.length+' found</span></div>'+(all.length?cards(all):'<div class="qr-empty">No approved cached reply matches “'+esc(q)+'”.<br>No price will be guessed.</div>');const r=recent(),f=favourites();let html='';if(r.length)html+='<div class="qr-section"><h3>Recently used</h3><span>Fast access</span></div>'+cards(r,'qr-grid');if(f.length)html+='<div class="qr-section"><h3>Favourites</h3><span>Your pinned replies</span></div>'+cards(f,'qr-grid');html+='<div class="qr-section"><h3>Screen Repairs</h3><span>'+all.length+' approved models</span></div>'+(all.length?cards(all):'<div class="qr-empty">No validated screen prices are available in the local cache.</div>');return html}
function syncHtml(){const v=payload.version,has=!!(v&&v.syncedAt),cached=!lastNetworkOk&&has;return '<div class="qr-sync"><div class="qr-sync-main"><b><i class="qr-status-dot '+(cached?'cached':'')+'"></i>'+(cached?'Cached prices active':'Prices last synchronised')+'</b>'+(has?esc(formatDate(v.syncedAt)):'No valid price version loaded')+(cached?'<span class="qr-offline-label"> · offline/cache mode</span>':'')+'</div><button class="qr-refresh" type="button" id="qrRefresh" '+(loading?'disabled':'')+'>'+(loading?'Refreshing…':'🔄 Refresh Current Prices')+'</button></div>'}
function view(){const count=templates().length;return '<section class="qr-hero"><div class="qr-kicker">PRIVATE · TECHNICIAN</div><h2>⚡ Quick Replies</h2><div class="muted">Tap a repair once. The complete approved response is copied immediately.</div><div class="qr-search-wrap"><input id="qrSearch" class="qr-search" type="search" inputmode="search" autocomplete="off" autocapitalize="none" placeholder="Search model or repair…" value="'+esc(query)+'"><span>⌕</span></div>'+syncHtml()+(notice?'<div class="qr-warning '+(noticeType==='success'?'qr-success':'')+'">'+esc(notice)+'</div>':'')+'</section><div id="qrResults">'+resultsHtml()+'</div>'+(count?'<div class="muted" style="margin:14px 2px">Replies use the current validated cache only. Stock is never assumed.</div>':'')}
function findTemplate(id){return templates().find(t=>t.id===id)||null}
function updateResults(){const node=document.querySelector('#qrResults');if(node)node.innerHTML=resultsHtml();bindCards()}
function showToast(text){let el=document.querySelector('#qrToast');if(!el){el=document.createElement('div');el.id='qrToast';el.className='qr-toast';document.body.appendChild(el)}el.textContent=text;requestAnimationFrame(()=>el.classList.add('show'));clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function showManual(text,title){manualText=text;const old=document.querySelector('#qrFallback');if(old)old.remove();const wrap=document.createElement('div');wrap.id='qrFallback';wrap.className='qr-fallback';wrap.innerHTML='<div class="qr-sheet"><h3>'+esc(title||'Copy reply')+'</h3><div class="muted" style="margin-bottom:8px">Automatic clipboard access was blocked. The complete reply is preserved below.</div><textarea id="qrManualText" readonly>'+esc(text)+'</textarea><div class="qr-sheet-actions"><button class="qr-close" type="button" data-qr-close>Close</button><button class="qr-copy-manual" type="button" id="qrManualCopy">Copy</button></div></div>';document.body.appendChild(wrap);const ta=wrap.querySelector('#qrManualText');ta.focus();ta.select();wrap.querySelector('[data-qr-close]').onclick=()=>wrap.remove();wrap.querySelector('#qrManualCopy').onclick=()=>copyText(manualText).then(ok=>{if(ok){showToast('✓ Copied');wrap.remove()}else{ta.focus();ta.select()}})}
async function copyText(text){try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text);return true}}catch(e){}try{const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();ta.setSelectionRange(0,ta.value.length);const ok=document.execCommand&&document.execCommand('copy');ta.remove();if(ok)return true}catch(e){}return false}
function bindCards(){document.querySelectorAll('[data-qr-copy]').forEach(btn=>btn.onclick=()=>{const t=findTemplate(btn.dataset.qrCopy);if(!t||!t.message){showToast('Reply unavailable — missing approved data');return}const attempt=copyText(t.message);const u=usageFor(t.id);setUsage(t.id,{count:Number(u.count||0)+1,lastUsed:new Date().toISOString()});attempt.then(ok=>{if(ok)showToast('✓ Copied — '+t.title);else showManual(t.message,t.title)})});document.querySelectorAll('[data-qr-fav]').forEach(btn=>btn.onclick=e=>{e.preventDefault();e.stopPropagation();const id=btn.dataset.qrFav,u=usageFor(id);setUsage(id,{favourite:!u.favourite});updateResults()})}
function bind(){const search=document.querySelector('#qrSearch');if(search)search.oninput=()=>{query=search.value;updateResults()};const refresh=document.querySelector('#qrRefresh');if(refresh)refresh.onclick=refreshPrices;bindCards()}
async function api(path,options){const opts=Object.assign({method:'GET',headers:{Accept:'application/json'}},options||{});const res=await fetch(API+path,opts);let data={};try{data=await res.json()}catch(e){}return{res,data}}
function acceptPayload(data){if(!data||!data.version||!Array.isArray(data.prices)||!data.prices.length)return false;const clean=data.prices.every(p=>p&&p.model_key&&p.model&&p.repair_type&&p.option_key&&Number.isFinite(Number(p.price))&&Number(p.price)>0);if(!clean)return false;payload={version:data.version,prices:data.prices};saveJson(PRICE_KEY,payload);return true}
async function load(){try{const{res,data}=await api('/pricing');if(res.ok&&acceptPayload(data)){lastNetworkOk=true;notice='';emit()}else{lastNetworkOk=false;if(!(payload.prices||[]).length){notice='No validated price cache is available yet.';noticeType='warning';emit()}}}catch(e){lastNetworkOk=false;if(!(payload.prices||[]).length){notice='Offline — no previously synced Quick Replies price cache is available on this device.';noticeType='warning';emit()}else emit()}}
async function refreshPrices(){if(loading)return;loading=true;notice='';emit();try{const{res,data}=await api('/pricing/refresh',{method:'POST'});if(data&&data.version&&data.prices)acceptPayload(data);if(res.ok&&data.ok){lastNetworkOk=true;notice='✅ Prices updated · '+Number(data.changed||0)+' changed · '+Number(data.unchanged||0)+' unchanged · synced '+formatDate(data.version&&data.version.syncedAt);noticeType='success'}else{lastNetworkOk=navigator.onLine;notice=(data&&data.message?data.message:'Price refresh failed.')+' Current cached prices were kept.';noticeType='warning'}}catch(e){lastNetworkOk=false;notice='Price source could not be reached. Current cached prices were kept.';noticeType='warning'}finally{loading=false;emit()}}
function setQuery(value){query=String(value||'');emit()}
g.IRepairQuickReplies={view,bind,load,refreshPrices,setQuery,templates,screenMessage,copyText};load();
})(window);