/* iRepair Repair Relay · Build 43 stable live/last-known journey map. */
(function(){
'use strict';
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/trip-api',KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L',token=new URLSearchParams(location.search).get('t')||'';
let trip=null,busy=false,last='';
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function getTrip(){const r=await fetch(API+'/relay/'+encodeURIComponent(token),{headers:{Accept:'application/json',Authorization:'Bearer '+KEY,apikey:KEY},cache:'no-store'}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d.trip||null}
function eta(){return trip&&trip.etaMinutes!=null?(trip.etaMinutes<=1?'Arriving shortly':trip.etaMinutes+' min'):'ETA updating'}
function dist(){return trip&&trip.distanceRemainingMiles!=null?Number(trip.distanceRemainingMiles).toFixed(1)+' miles away':''}
function key(t){const l=t&&t.approxLocation||{};return t?[t.state,t.live,l.latitude,l.longitude,t.etaMinutes,t.distanceRemainingMiles,t.locationUpdatedAt,t.locationAgeSeconds].join('|'):'none'}
function ageText(){const s=Number(trip&&trip.locationAgeSeconds);if(!Number.isFinite(s))return 'Last position available';if(s<60)return 'Updated less than a minute ago';const m=Math.max(1,Math.round(s/60));return 'Updated about '+m+' min ago'}
function tiles(loc){const lat=Math.max(-85.05112878,Math.min(85.05112878,Number(loc.latitude))),lng=Number(loc.longitude),z=15,S=256,n=2**z,wx=(lng+180)/360*n*S,sin=Math.sin(lat*Math.PI/180),wy=(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*n*S,cx=Math.floor(wx/S),cy=Math.floor(wy/S),px=wx-cx*S,py=wy-cy*S;let imgs='';for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){const tx=(cx+x+n)%n,ty=Math.max(0,Math.min(n-1,cy+y));imgs+='<img alt="" draggable="false" src="https://tile.openstreetmap.org/'+z+'/'+tx+'/'+ty+'.png" style="left:'+((x+1)*S)+'px;top:'+((y+1)*S)+'px">'}const left=Math.round(250-(S+px)),top=Math.round(135-(S+py)),fresh=!!trip.live,label=fresh?'LIVE':'LAST KNOWN',sub=fresh?(dist()||'Heading to you'):ageText();return '<div class="r43map"><div class="r43tiles" style="left:'+left+'px;top:'+top+'px">'+imgs+'</div><div class="r43fade top"></div><div class="r43badge '+(fresh?'live':'stale')+'"><span><i></i>'+label+'</span><strong>'+esc(eta())+'</strong><small>'+esc(sub)+'</small></div><div class="r43van">🚐</div><div class="r43fade bottom"></div><div class="r43caption"><b>Technician on the way</b><span>Approximate position · exact GPS hidden</span></div><a class="r43attr" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap</a></div>'}
function render(force){const root=document.getElementById('root');if(!root)return;const k=key(trip);if(!force&&k===last)return;last=k;let el=root.querySelector('.r43trip');if(!trip||!['en_route','arrived'].includes(trip.state)){if(el)el.remove();return}if(!el){el=document.createElement('section');el.className='card r43trip';const cards=root.querySelectorAll('section.card');(cards[0]||root).insertAdjacentElement(cards[0]?'afterend':'afterbegin',el)}if(trip.state==='arrived'){el.innerHTML='<div class="eyebrow">JOURNEY UPDATE</div><div class="r43arrived"><strong>📍 Technician arrived</strong><span>The technician has reached the repair location.</span></div>';return}const map=trip.approxLocation?tiles(trip.approxLocation):'<div class="r43wait"><b>Live location starting…</b><span>The technician device is connecting to the journey tracker.</span></div>';el.innerHTML='<div class="eyebrow">LIVE JOURNEY</div><h2>Technician en route</h2><div class="muted">'+(trip.live?'Live journey tracking':'Showing the last known journey position')+'</div>'+map+'<div class="r43stats"><div><small>ETA</small><b>'+esc(eta())+'</b></div><div><small>DISTANCE</small><b>'+esc(dist()||'Updating')+'</b></div><div><small>PRIVACY</small><b>Approximate</b></div></div><div class="r43safe">🔒 Relay only receives a softened technician position, never the precise GPS coordinates.</div>'}
async function load(){if(!token||busy)return;busy=true;try{trip=await getTrip();render(false)}catch(e){}finally{busy=false}}
const css=document.createElement('style');css.textContent=`.r43trip{border-color:#397aa7!important;background:linear-gradient(145deg,#103a59,#0b253b)!important;overflow:hidden}.r43trip>h2{font-size:20px;margin:5px 0 3px}.r43map{position:relative;height:270px;margin:13px -16px 4px;overflow:hidden;background:#dce5ea}.r43tiles{position:absolute;width:768px;height:768px}.r43tiles img{position:absolute;width:256px;height:256px;max-width:none;-webkit-user-drag:none}.r43fade{position:absolute;z-index:2;left:0;right:0;height:86px;pointer-events:none}.r43fade.top{top:0;background:linear-gradient(#071a2ccc,transparent)}.r43fade.bottom{bottom:0;background:linear-gradient(transparent,#071a2ce8)}.r43badge{position:absolute;z-index:5;left:12px;top:11px;padding:8px 11px;border-radius:15px;background:#071a2ddd;border:1px solid #8ac9f455;display:grid;grid-template-columns:auto auto;gap:0 9px;align-items:center;box-shadow:0 8px 22px #0005}.r43badge>span{grid-row:1/3;font-size:8px;font-weight:900;letter-spacing:.06em;color:#b9ddf4}.r43badge i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px;background:#58f27f;box-shadow:0 0 9px #58f27f}.r43badge.stale i{background:#f5b84f;box-shadow:0 0 9px #f5b84f}.r43badge strong{font-size:20px}.r43badge small{font-size:8px;color:#a8c8df}.r43van{position:absolute;z-index:6;left:50%;top:52%;width:52px;height:52px;margin:-26px;border-radius:50%;display:grid;place-items:center;background:#0c72dfee;border:3px solid #fff;box-shadow:0 0 0 10px #158cff2c,0 10px 26px #00152e88;font-size:24px}.r43caption{position:absolute;z-index:5;left:12px;right:12px;bottom:10px;display:flex;justify-content:space-between;gap:10px;color:white}.r43caption b{font-size:12px}.r43caption span{font-size:8px;color:#a9c9df;text-align:right}.r43attr{position:absolute;z-index:5;right:5px;bottom:1px;font-size:6.5px;color:#e4f3fb;background:#071a2da8;padding:2px 4px;border-radius:4px;text-decoration:none}.r43stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.r43stats div{padding:9px 8px;border-radius:12px;background:#081724;border:1px solid #294861}.r43stats small{display:block;font-size:7px;font-weight:900;letter-spacing:.07em;color:#7199b7;margin-bottom:4px}.r43stats b{font-size:10px}.r43safe{margin-top:10px;padding-top:9px;border-top:1px solid #ffffff18;color:#7fa4c0;font-size:9px;line-height:1.4}.r43wait{height:190px;margin:13px -16px 4px;display:grid;place-content:center;text-align:center;gap:5px;background:#081724}.r43wait b{font-size:14px}.r43wait span{font-size:9px;color:#8caec8}.r43arrived{display:grid;gap:4px;margin-top:9px;padding:13px;border-radius:15px;background:#0b281e;border:1px solid #3f7b5e}.r43arrived strong{font-size:18px;color:#d8ffe6}.r43arrived span{font-size:10px;color:#99c7aa}@media(max-width:390px){.r43map{height:240px}.r43stats{grid-template-columns:1fr 1fr}.r43stats div:last-child{grid-column:1/-1}}`;document.head.appendChild(css);
window.addEventListener('irepair-relay-rendered',()=>render(true));load();setInterval(()=>{if(document.visibilityState!=='hidden')load()},5000);
})();