/* iRepair Repair Relay · Build 36 journey/ETA display. */
(function(){
'use strict';
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/trip-api';
const KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const token=new URLSearchParams(location.search).get('t')||'';
let trip=null,timer=null,loading=false;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(){const r=await fetch(API+'/relay/'+encodeURIComponent(token),{headers:{Accept:'application/json',Authorization:'Bearer '+KEY,apikey:KEY}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function copy(){if(!trip)return null;const state=trip.state||'idle';if(state==='en_route'){const eta=trip.etaMinutes==null?'ETA updating':(trip.etaMinutes<=1?'Arriving shortly':trip.etaMinutes+' min');const detail=[];if(trip.distanceRemainingMiles!=null)detail.push(Number(trip.distanceRemainingMiles).toFixed(1)+' miles remaining');if(trip.provider==='google_navigation_connect'||trip.provider==='google_routes')detail.push('live navigation');return{cls:'enroute',eyebrow:'LIVE JOURNEY',title:'🚐 Technician en route',value:eta,detail:detail.join(' · ')||'Journey started. Live ETA will appear automatically when navigation reporting is connected.'}}if(state==='arrived')return{cls:'arrived',eyebrow:'JOURNEY UPDATE',title:'📍 Technician arrived',value:'Arrived',detail:'The technician has reached the repair location.'};return null}
function render(){const root=document.getElementById('root');if(!root)return;let el=root.querySelector('.relay36-trip');const c=copy();if(!c){if(el)el.remove();return}if(!el){el=document.createElement('section');el.className='card relay36-trip';const first=root.querySelector('section.card');if(first)first.insertAdjacentElement('afterend',el);else root.prepend(el)}el.className='card relay36-trip '+c.cls;el.innerHTML='<div class="eyebrow">'+esc(c.eyebrow)+'</div><div class="relay36-row"><div><h2>'+esc(c.title)+'</h2><div class="muted">'+esc(c.detail)+'</div></div><strong>'+esc(c.value)+'</strong></div><div class="relay36-safe">🔒 Repair Relay receives ETA and journey progress only — not the technician’s precise live pin.</div>'}
async function load(){if(!token||loading)return;loading=true;try{const d=await api();trip=d.trip||null;render()}catch(e){trip=null;render()}finally{loading=false}}
const style=document.createElement('style');style.textContent='.relay36-trip{border-color:#397aa7;background:linear-gradient(145deg,#103a59,#0b253b)}.relay36-trip.arrived{border-color:#3f7b5e;background:linear-gradient(145deg,#123a2d,#0c2c22)}.relay36-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.relay36-row h2{font-size:18px;margin:5px 0 4px}.relay36-row>strong{font-size:22px;color:#bfe8ff;white-space:nowrap}.relay36-trip.arrived .relay36-row>strong{color:#cef4dc}.relay36-safe{margin-top:10px;padding-top:9px;border-top:1px solid #ffffff18;color:#7fa4c0;font-size:9px;line-height:1.4}';document.head.appendChild(style);
new MutationObserver(()=>requestAnimationFrame(render)).observe(document.getElementById('root'),{childList:true,subtree:true});load();timer=setInterval(()=>{if(document.visibilityState!=='hidden')load()},5000);
})();