/* iRepair Technician · Build 37 live trip bridge for customer app + Repair Relay.
   Only the browser that selects "On my way" becomes the live journey source. */
(function(){
'use strict';
if(window.__IREPAIR_TRIP37_LOADED)return;window.__IREPAIR_TRIP37_LOADED=true;
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/trip-api';
const KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const LIVE_KEY='irepair_live_journey_job_v1';
const sent=new Map();
let geoWatch=null,geoJob='',lastGeoPush=0,geoState='idle',lastAccuracy=null;
function tripState(status){return status==='on_my_way'?'en_route':status==='arrived'?'arrived':status==='completed'?'completed':status==='cancelled'?'cancelled':'planned'}
async function post(jobId,body){const r=await fetch(API+'/jobs/'+encodeURIComponent(jobId),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer '+KEY,apikey:KEY},body:JSON.stringify(body||{})});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function sync(job){if(!job||!job.id)return;const state=tripState(job.status),fingerprint=state;if(sent.get(job.id)===fingerprint)return;sent.set(job.id,fingerprint);try{await post(job.id,{state})}catch(e){sent.delete(job.id)}}
function liveId(){try{return localStorage.getItem(LIVE_KEY)||''}catch(e){return ''}}
function setLiveId(id){try{id?localStorage.setItem(LIVE_KEY,id):localStorage.removeItem(LIVE_KEY)}catch(e){}}
function indicatorCopy(){if(geoState==='live')return{cls:'live',title:'🟢 Customer live journey active',text:'Approximate map updates are being sent'+(lastAccuracy!=null?' · GPS accuracy '+Math.round(lastAccuracy)+' m':'')+'. Exact coordinates remain private.'};if(geoState==='requesting')return{cls:'starting',title:'📍 Starting customer live journey…',text:'Allow location access on this technician device when prompted.'};if(geoState==='denied')return{cls:'warning',title:'⚠ Live journey location is blocked',text:'Enable Location permission for this site. The customer can see “On my way”, but the moving map cannot update.'};if(geoState==='unsupported')return{cls:'warning',title:'⚠ Live location unavailable',text:'This browser does not support the journey location feed.'};if(geoState==='unavailable')return{cls:'warning',title:'⚠ Waiting for GPS',text:'The customer journey is active, but a fresh location fix is not currently available.'};return{cls:'starting',title:'📍 Customer journey armed',text:'Waiting for the technician location feed to start.'}}
function renderIndicator(){document.querySelectorAll('.trip37-tech-status').forEach(x=>x.remove());const id=liveId();if(!id)return;const opener=document.querySelector('[data-open="'+CSS.escape(id)+'"]'),card=opener&&opener.closest('article.job');if(!card)return;const c=indicatorCopy(),el=document.createElement('div');el.className='trip37-tech-status '+c.cls;el.innerHTML='<strong>'+c.title+'</strong><span>'+c.text+'</span>';const actions=card.querySelector('.actions');if(actions)actions.insertAdjacentElement('beforebegin',el);else card.appendChild(el)}
function emit(state,accuracy){geoState=state;if(accuracy!=null)lastAccuracy=accuracy;window.dispatchEvent(new CustomEvent('irepair-trip-location',{detail:{state,accuracy:lastAccuracy}}));renderIndicator()}
function stopGeo(){if(geoWatch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(geoWatch);geoWatch=null;geoJob='';lastAccuracy=null;emit('idle')}
function pushGeo(jobId,pos){if(!pos||!pos.coords||jobId!==liveId())return;const now=Date.now();if(now-lastGeoPush<12000)return;lastGeoPush=now;emit('live',pos.coords.accuracy);post(jobId,{state:'en_route',latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMetres:pos.coords.accuracy,headingDegrees:Number.isFinite(pos.coords.heading)?pos.coords.heading:null}).catch(()=>{})}
function startGeo(jobId){if(geoWatch!==null&&geoJob===jobId){renderIndicator();return}stopGeo();if(!navigator.geolocation){emit('unsupported');return}geoJob=jobId;emit('requesting');geoWatch=navigator.geolocation.watchPosition(p=>pushGeo(jobId,p),e=>emit(e&&e.code===1?'denied':'unavailable'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function syncLiveWatch(){const id=liveId();if(!id){if(geoWatch!==null)stopGeo();else renderIndicator();return}const job=DB.getJob(id);if(!job||job.status!=='on_my_way'){setLiveId('');stopGeo();return}startGeo(id)}
function syncAll(){DB.listJobs().forEach(sync);syncLiveWatch();renderIndicator()}
function wrapStatus(){if(typeof DB.setStatus!=='function'||DB.setStatus.__trip37)return;const original=DB.setStatus;const wrapped=function(id,status,source){const out=original.call(DB,id,status,source);if(status==='on_my_way'){setLiveId(id);setTimeout(syncLiveWatch,0)}else if(['arrived','completed','cancelled'].includes(status)&&liveId()===id){setLiveId('');stopGeo()}return out};wrapped.__trip37=true;DB.setStatus=wrapped}
const style=document.createElement('style');style.id='trip37TechStyle';style.textContent=`.trip37-tech-status{display:grid;gap:3px;margin:9px 0;padding:10px 11px;border-radius:12px;border:1px solid rgba(83,222,255,.36);background:rgba(10,78,119,.22)}.trip37-tech-status strong{font-size:10.5px;color:#d7f5ff}.trip37-tech-status span{font-size:9px;line-height:1.4;color:#8db6d1}.trip37-tech-status.live{border-color:rgba(83,239,134,.42);background:rgba(21,123,70,.20)}.trip37-tech-status.live strong{color:#d8ffe5}.trip37-tech-status.warning{border-color:rgba(255,188,77,.43);background:rgba(145,90,15,.20)}.trip37-tech-status.warning strong{color:#ffe1aa}`;document.head.appendChild(style);
wrapStatus();DB.subscribe(syncAll);DB.subscribeConnection(syncAll);window.addEventListener('irepair-api-change',syncAll);window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncLiveWatch()});new MutationObserver(()=>requestAnimationFrame(renderIndicator)).observe(document.body,{childList:true,subtree:true});syncAll();setInterval(()=>{if(document.visibilityState!=='hidden')syncAll()},30000);
})();