/* iRepair Technician · core interface. Build 23 adds Quick Replies without changing job/customer data flows. */
(function(){
'use strict';
const $=s=>document.querySelector(s);let view='jobs',selected=null,filter='all';
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const money=v=>typeof v==='number'?'£'+v.toFixed(2).replace('.00',''):'TBC';
function online(){return !!(IRepairDB.connection&&IRepairDB.connection.online)}
function coreChip(){const c=$('#coreChip');if(!c)return;c.textContent=online()?'CORE ONLINE':'CORE SYNC';c.classList.toggle('online',online())}
function counts(j){return{booked:j.filter(x=>['booked','confirmed'].includes(x.status)).length,active:j.filter(x=>['on_my_way','arrived','repairing','waiting_part'].includes(x.status)).length,done:j.filter(x=>x.status==='completed').length,due:j.filter(x=>x.paymentState!=='paid'&&x.status!=='cancelled').length}}
function hero(){const jobs=IRepairDB.listJobs(),c=counts(jobs),cn=IRepairDB.connection||{};return '<section class="hero"><div class="eyebrow">TODAY · TECHNICIAN VIEW</div><h2>Repair operations</h2><div class="muted">Customer and technician apps are sharing the Supabase-backed iRepair Core database.</div><div class="sync"><span><i class="dot '+(online()?'online':'')+'"></i><b>'+(online()?'Shared Core online':'Local cache / reconnecting')+'</b></span><span>'+(online()&&cn.lastSuccess?'Synced '+new Date(cn.lastSuccess).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'Auto-sync every few seconds')+'</span></div><div class="kpis"><div class="kpi"><strong>'+c.booked+'</strong><span>BOOKED</span></div><div class="kpi"><strong>'+c.active+'</strong><span>ACTIVE</span></div><div class="kpi"><strong>'+c.done+'</strong><span>DONE</span></div><div class="kpi"><strong>'+c.due+'</strong><span>PAYMENT DUE</span></div></div></section>'}
function visible(){let a=IRepairDB.listJobs();if(filter==='action')a=a.filter(j=>!['completed','cancelled'].includes(j.status));if(filter==='parts')a=a.filter(j=>j.status==='waiting_part'||['order_required','ordered'].includes(j.partState));if(filter==='done')a=a.filter(j=>j.status==='completed');return a}
function nextStatus(j){const o=['booked','confirmed','on_my_way','arrived','repairing','completed'];let i=o.indexOf(j.status);return o[Math.min(o.length-1,Math.max(0,i+1))]}
function buttons(list,current,attr,cls){return '<div class="chooser '+(cls||'')+'">'+list.map(x=>'<button class="'+(x[0]===current?'active':'')+'" '+attr+'="'+esc(x[0])+'">'+esc(x[1])+'</button>').join('')+'</div>'}
function workflow(j){const history=(j.timeline||[]).map(e=>String(e.label||'').toLowerCase()).join(' | '),seen=t=>history.includes(String(t).toLowerCase()),rank={booked:0,confirmed:1,waiting_part:1,on_my_way:2,arrived:3,repairing:4,completed:5,cancelled:-1},at=s=>(rank[j.status]??-1)>=(rank[s]??99)||seen(IRepairDB.label(s)),orderNeeded=['order_required','ordered','received'].includes(j.partState)||seen('order required'),ordered=['ordered','received'].includes(j.partState)||seen('ordered'),stocked=['in_stock','received','fitted'].includes(j.partState)||seen('in stock')||seen('received')||seen('fitted'),orderSkipped=stocked&&!orderNeeded&&!ordered;const steps=[['Customer booked',true,'Repair request received'],['Booking confirmed',at('confirmed'),''],['Part needs ordering',orderNeeded,orderSkipped?'Not needed':''],['Part ordered',ordered,orderSkipped?'Not needed':''],['Part in stock',stocked,''],['Technician on way',at('on_my_way'),''],['Arrived',at('arrived'),''],['Repairing',at('repairing'),''],['Repair complete',at('completed'),''],['Payment complete',j.paymentState==='paid','']];return '<div class="section"><h3>Workflow at a glance</h3><span>Green = completed</span></div><div class="workflow">'+steps.map(s=>'<div class="workflow-step '+(s[1]?'done':s[2]?'skipped':'')+'"><span class="workflow-mark">'+(s[1]?'✓':'·')+'</span><span><b>'+esc(s[0])+'</b>'+(s[2]?'<small>'+esc(s[2])+'</small>':'')+'</span></div>').join('')+'</div>'}
function observationBlock(j){const rows=(j.observations||[]).slice().reverse();return '<div class="section"><h3>Repair observations</h3><span>Comeback protection</span></div>'+(rows.length?rows.map(o=>'<div class="record obs '+(o.customerAdvised?'advised':'')+'"><b>'+esc(IRepairDB.observationLabel(o.category))+'</b><div class="muted" style="margin-top:4px">'+esc(o.note)+'</div><div class="tags"><span class="tag '+(o.customerAdvised?'good':'warn')+'">'+(o.customerAdvised?'Customer advised ✓':'Not marked advised')+'</span>'+(o.customerVisible?'<span class="tag good">Visible to customer</span>':'<span class="tag">Internal record</span>')+'</div></div>').join(''):'<div class="empty">No observations recorded.</div>')+'<select class="field" id="obsCategory">'+IRepairDB.OBSERVATION_CATEGORIES.map(x=>'<option value="'+esc(x[0])+'">'+esc(x[1])+'</option>').join('')+'</select><textarea class="field text" id="obsText" placeholder="e.g. Battery slightly swollen. Customer advised that replacement is recommended."></textarea><div class="checks"><label class="check"><input type="checkbox" id="obsAdvised">Customer advised</label><label class="check"><input type="checkbox" id="obsVisible">Show in customer app</label></div><button class="btn secondary" style="width:100%;margin-top:7px" data-observation="'+esc(j.id)+'">Save observation</button>'}
function chatBlock(j){const rows=(j.messages||[]).slice(-12);return '<div class="section"><h3>Customer chat</h3><span>Refreshes every few seconds</span></div><div class="chat">'+(rows.length?rows.map(m=>'<div class="msg '+(m.senderRole==='technician'?'tech':'')+'"><b>'+esc(m.senderName||m.senderRole)+'</b><br>'+esc(m.body)+'<small>'+new Date(m.at).toLocaleString('en-GB')+'</small></div>').join(''):'<div class="muted">No chat messages yet.</div>')+'</div><div class="quick"><button data-template="issue">Advise issue</button><button data-template="battery">Battery approval</button><button data-template="unlock">Need unlock access</button></div><textarea class="field text" id="chatText" placeholder="Message the customer about this repair…"></textarea><button class="btn" style="width:100%;margin-top:7px" data-sendchat="'+esc(j.id)+'">Send message</button><div class="warning"><b>Device passcodes:</b> do not type or store passcodes in this chat. A temporary secure credential request will be added after authenticated customer accounts are enabled.</div>'}
function contactsBlock(j){const rows=j.contacts||[];return '<div class="section"><h3>Secondary contact</h3><span>Job-specific contact</span></div>'+(rows.length?rows.map(c=>'<div class="record"><b>'+esc(c.fullName)+'</b><div class="muted">'+esc(c.relationship||'Secondary contact')+(c.phone?' · '+esc(c.phone):'')+(c.email?' · '+esc(c.email):'')+'</div><div class="tags">'+(c.receivesUpdates?'<span class="tag good">Receives repair updates</span>':'<span class="tag">No updates</span>')+'<span class="tag">Not a marketing contact by default</span></div></div>').join(''):'<div class="empty">No secondary contact added.</div>')+'<div class="two"><input class="field" id="contactName" placeholder="Name"><input class="field" id="contactRelationship" placeholder="Friend, partner, parent…"></div><div class="two"><input class="field" id="contactPhone" placeholder="Mobile number"><input class="field" id="contactEmail" placeholder="Email (optional)"></div><div class="checks"><label class="check"><input type="checkbox" id="contactUpdates" checked>Send repair updates</label><label class="check"><input type="checkbox" id="contactHandover">Main handover contact</label></div><button class="btn secondary" style="width:100%;margin-top:7px" data-contact="'+esc(j.id)+'">Add secondary contact</button><div class="muted" style="margin-top:7px">This person can later be invited to iRepair. They only become their own customer/marketing contact if they onboard or consent themselves.</div>'}
function detail(j){if(selected!==j.id)return '';const loc=[j.address,j.postcode].filter(Boolean).join(', '),map=loc?'https://maps.apple.com/?q='+encodeURIComponent(loc):'';return '<div class="detail"><div class="grid2"><div class="box"><strong>CUSTOMER</strong><span>'+esc(j.customerName)+'</span></div><div class="box"><strong>DEVICE</strong><span>'+esc(j.device)+(j.variant?'<br>'+esc(j.variant):'')+'</span></div><div class="box"><strong>LOCATION</strong><span>'+esc(loc||'Not set')+'</span></div><div class="box"><strong>COMPATIBILITY</strong><span>'+esc(j.compatibility)+'</span></div></div>'+workflow(j)+'<div class="toolbar">'+(j.phone?'<a class="btn secondary" href="tel:'+esc(j.phone)+'">Call</a>':'')+(map?'<a class="btn secondary" href="'+map+'" target="_blank">Navigate</a>':'')+'</div><div class="section"><h3>Repair status</h3><span>Customer sees this</span></div>'+buttons(IRepairDB.STATUS,j.status,'data-status','')+'<div class="section"><h3>Part / stock</h3><span>Internal</span></div>'+buttons(IRepairDB.PART_STATES,j.partState,'data-part','parts')+'<div class="two"><input class="field" id="partName" value="'+esc(j.partName||'')+'" placeholder="Part / colour"><input class="field" id="supplier" value="'+esc(j.supplier||'')+'" placeholder="Supplier"></div><button class="btn secondary" style="width:100%;margin-top:7px" data-partinfo="'+esc(j.id)+'">Save part details</button><div class="section"><h3>Payment</h3><span>'+money(j.price)+'</span></div>'+buttons(IRepairDB.PAYMENT_STATES,j.paymentState,'data-pay','pay')+observationBlock(j)+chatBlock(j)+contactsBlock(j)+'<div class="section"><h3>Additional technician note</h3><span>Internal only</span></div><textarea class="field text" id="noteText" placeholder="Anything else you want retained against the repair…"></textarea><button class="btn secondary" style="width:100%;margin-top:7px" data-note="'+esc(j.id)+'">Save internal note</button><div class="section"><h3>Timeline</h3><span>Core events</span></div><div class="timeline">'+((j.timeline||[]).slice().reverse().slice(0,12).map(e=>'<div class="event"><b>'+esc(e.label)+'</b><br>'+esc(e.actor)+' · '+new Date(e.at).toLocaleString('en-GB')+(e.visibility==='internal'?' · internal':'')+'</div>').join('')||'No events yet.')+'</div></div>'}
function card(j){return '<article class="job"><div class="jobhead"><div><h4>'+esc(j.device)+'</h4><div class="ref">'+esc(j.id)+' · '+esc(j.customerName)+'</div></div><div style="text-align:right"><span class="status '+esc(j.status)+'">'+esc(IRepairDB.label(j.status))+'</span><div class="price">'+money(j.price)+'</div></div></div><div class="tags"><span class="tag">'+esc(j.repair)+'</span><span class="tag">'+esc(j.service)+'</span>'+(j.postcode?'<span class="tag">'+esc(j.postcode)+'</span>':'')+(j.slot?'<span class="tag">'+esc(j.slot)+'</span>':'')+'<span class="tag '+(['in_stock','fitted','received'].includes(j.partState)?'good':j.partState==='not_checked'?'':'warn')+'">Part: '+esc(IRepairDB.partLabel(j.partState))+'</span><span class="tag '+(j.paymentState==='paid'?'good':'due')+'">'+esc(IRepairDB.paymentLabel(j.paymentState))+'</span>'+(j.observations&&j.observations.length?'<span class="tag warn">'+j.observations.length+' observation'+(j.observations.length===1?'':'s')+'</span>':'')+'</div><div class="actions"><button class="btn secondary" data-open="'+esc(j.id)+'">'+(selected===j.id?'Close':'Open job')+'</button><button class="btn" data-next="'+esc(j.id)+'">Next status →</button></div>'+detail(j)+'</article>'}
function jobsView(){const jobs=visible();return hero()+'<div class="toolbar"><button class="btn" id="syncNow">Sync Core</button><button class="btn secondary" id="newDemo">+ Demo booking</button></div><div class="filters">'+[['all','All'],['action','Needs action'],['parts','Parts'],['done','Completed']].map(f=>'<button class="filter '+(filter===f[0]?'active':'')+'" data-filter="'+f[0]+'">'+f[1]+'</button>').join('')+'</div><div class="section"><h3>Job queue</h3><span>'+jobs.length+' shown</span></div>'+(jobs.length?jobs.map(card).join(''):'<div class="empty">No repairs in this view.</div>')}
function routeView(){const jobs=IRepairDB.listJobs().filter(j=>!['completed','cancelled'].includes(j.status)&&/mobile/i.test(j.service)).sort((a,b)=>String(a.slot||'').localeCompare(String(b.slot||'')));return hero()+'<div class="section"><h3>Today’s mobile route</h3><span>'+jobs.length+' stops</span></div>'+(jobs.length?jobs.map((j,i)=>{const loc=[j.address,j.postcode].filter(Boolean).join(', ');return '<div class="route"><div class="route-row"><div><span class="route-num">'+(i+1)+'</span><b>'+esc(j.customerName)+'</b></div><span class="status '+esc(j.status)+'">'+esc(IRepairDB.label(j.status))+'</span></div><div class="muted" style="margin:8px 0">'+esc(j.device)+' · '+esc(j.repair)+'<br>'+esc(j.slot||'Time TBC')+' · '+esc(loc||'Location TBC')+'</div>'+(loc?'<a href="https://maps.apple.com/?q='+encodeURIComponent(loc)+'" target="_blank">Open navigation →</a>':'')+'</div>'}).join(''):'<div class="empty">No active mobile jobs.</div>')}
function customersView(){const map={};IRepairDB.listJobs().forEach(j=>{const k=j.customerName||'Unknown';if(!map[k])map[k]={name:k,jobs:0,devices:new Set(),spent:0};map[k].jobs++;map[k].devices.add(j.device);if(j.status==='completed'&&typeof j.price==='number')map[k].spent+=j.price});const arr=Object.values(map);return hero()+'<div class="section"><h3>Demo customers</h3><span>'+arr.length+' records</span></div>'+(arr.length?arr.map(c=>'<div class="customer"><b>'+esc(c.name)+'</b><div class="muted">'+c.jobs+' repair'+(c.jobs===1?'':'s')+' · '+c.devices.size+' device'+(c.devices.size===1?'':'s')+' · completed spend '+money(c.spent)+'</div></div>').join(''):'<div class="empty">No customer records yet.</div>')}
function repliesView(){return window.IRepairQuickReplies?IRepairQuickReplies.view():'<div class="empty">Quick Replies could not be loaded.</div>'}
function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));$('#main').innerHTML=view==='route'?routeView():view==='customers'?customersView():view==='replies'?repliesView():jobsView();bind();coreChip()}
function bind(){
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;selected=null;render()});
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{selected=selected===b.dataset.open?null:b.dataset.open;render()});
 document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const j=IRepairDB.getJob(b.dataset.next);if(j){IRepairDB.setStatus(j.id,nextStatus(j),'technician');selected=j.id;render()}});
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{IRepairDB.setStatus(selected,b.dataset.status,'technician');render()});
 document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{IRepairDB.setPartState(selected,b.dataset.part,'technician');render()});
 document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>{IRepairDB.setPaymentState(selected,b.dataset.pay,'technician');render()});
 document.querySelectorAll('[data-partinfo]').forEach(b=>b.onclick=()=>{IRepairDB.updateJob(b.dataset.partinfo,{partName:$('#partName').value.trim(),supplier:$('#supplier').value.trim()},'technician');render()});
 document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{const t=$('#noteText');if(t&&t.value.trim()){IRepairDB.addNote(b.dataset.note,t.value,'Technician','technician');render()}});
 document.querySelectorAll('[data-observation]').forEach(b=>b.onclick=()=>{const t=$('#obsText');if(t&&t.value.trim()){IRepairDB.addObservation(b.dataset.observation,{category:$('#obsCategory').value,note:t.value,customerAdvised:$('#obsAdvised').checked,customerVisible:$('#obsVisible').checked},'technician');render()}});
 document.querySelectorAll('[data-sendchat]').forEach(b=>b.onclick=()=>{const t=$('#chatText');if(t&&t.value.trim()){IRepairDB.sendMessage(b.dataset.sendchat,t.value,'technician','Simon · iRepair','chat','technician');render()}});
 document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=$('#chatText');if(!t)return;const q={issue:'I have noticed something while working on your device that I would like to make you aware of.',battery:'It appears that your device would benefit from a new battery. Are you happy for me to proceed?',unlock:'I need to unlock the device to complete testing. Please contact me so we can arrange secure access without putting your passcode in chat.'};t.value=q[b.dataset.template]||'';t.focus()});
 document.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>{const n=$('#contactName');if(n&&n.value.trim()){IRepairDB.addSecondaryContact(b.dataset.contact,{fullName:n.value,relationship:$('#contactRelationship').value,phone:$('#contactPhone').value,email:$('#contactEmail').value,receivesUpdates:$('#contactUpdates').checked,isPrimaryHandoverContact:$('#contactHandover').checked},'technician');render()}});
 const sy=$('#syncNow');if(sy)sy.onclick=()=>IRepairDB.syncRemote().then(render);const nd=$('#newDemo');if(nd)nd.onclick=()=>{const j=IRepairDB.createDemoBooking();selected=j.id;render()};
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;selected=null;render()});
 if(view==='replies'&&window.IRepairQuickReplies)IRepairQuickReplies.bind();
}
function coreUpdate(){if(view==='replies')coreChip();else render()}
IRepairDB.subscribe(coreUpdate);IRepairDB.subscribeConnection(coreUpdate);
window.addEventListener('irepair-quick-replies-change',()=>{if(view==='replies')render()});
render();
})();