/* iRepair Technician · Build 36 route-aware Satellite suggestions.
   Suggestions never reorder the diary unless the technician explicitly accepts them. */
(function(){
'use strict';
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/satellite-api';
const API_KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const LOCKED=new Set(['on_my_way','arrived','repairing']);
const INACTIVE=new Set(['completed','cancelled']);
let status=null,scheduled=false,loading=false;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/json',Authorization:'Bearer '+API_KEY,apikey:API_KEY}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function satelliteEvent(job){return (job&&job.timeline||[]).slice().reverse().find(e=>e&&e.type==='satellite')||null}
function parse(label){const s=String(label||''),detour=s.match(/\+(\d+) min detour/i),approach=s.match(/(\d+) min drive to customer/i),before=s.match(/suggested before (IR-[A-Z0-9-]+)/i);return{traffic:/traffic-aware route/i.test(s),fallback:/proximity fallback/i.test(s),office:/office availability/i.test(s),extraDriveMinutes:detour?Number(detour[1]):null,approachMinutes:approach?Number(approach[1]):null,beforeRef:before?before[1]:''}}
function engineText(){const r=status&&status.routing||status&&status.satellite&&status.satellite.routing||{};if(r.provider==='google_routes')return '<b>🧭 Traffic-aware route matching active</b><span>Live road travel and detour scoring are available for Satellite matching.</span>';return '<b>🧭 Route engine ready</b><span>Satellite is using proximity matching until the Google traffic-routing credential is connected.</span>'}
function profileText(){const s=status&&status.satellite||{},m=s.detourMode||'route_only',labels={route_only:'Route only · up to 8 min extra driving',nearby:'Nearby · up to 15 min extra driving',open:'Open · up to 30 min extra driving'};return labels[m]||labels.route_only}
function currentOrder(){const all=DB.listJobs().filter(j=>!INACTIVE.has(j.status));const dom=[...document.querySelectorAll('#main article.job')].map(c=>{const o=c.querySelector('[data-open]');return o&&o.dataset.open}).filter(Boolean);const seen=new Set(dom),tail=all.filter(j=>!seen.has(j.id)).sort((a,b)=>{const ao=Number(a.scheduleOrder),bo=Number(b.scheduleOrder),af=Number.isFinite(ao),bf=Number.isFinite(bo);if(af&&bf&&ao!==bo)return ao-bo;if(af!==bf)return af?-1:1;return String(a.slot||'').localeCompare(String(b.slot||''))}).map(j=>j.id);return dom.concat(tail)}
function suggestedOrder(jobId,beforeRef){const ids=currentOrder().filter(id=>id!==jobId),target=ids.indexOf(beforeRef);if(target>=0)ids.splice(target,0,jobId);else ids.push(jobId);return ids}
function alreadySuggested(jobId,beforeRef){const ids=currentOrder(),i=ids.indexOf(jobId),t=ids.indexOf(beforeRef);return i>=0&&t>=0&&i+1===t}
function enhanceEngine(){const panel=document.getElementById('satellite34');if(!panel)return;let box=panel.querySelector('.route36-engine');if(!box){box=document.createElement('div');box.className='route36-engine';const privacy=panel.querySelector('.sat34-privacy');if(privacy)privacy.insertAdjacentElement('beforebegin',box);else panel.appendChild(box)}box.innerHTML=engineText()+'<small>'+esc(profileText())+'</small>'}
function suggestionMarkup(job,meta){
 if(meta.office)return '';
 if(meta.traffic){const facts=[];if(meta.approachMinutes!=null)facts.push(meta.approachMinutes+' min drive to customer');if(meta.extraDriveMinutes!=null)facts.push('+'+meta.extraDriveMinutes+' min estimated detour');const target=meta.beforeRef?('Suggested before '+meta.beforeRef):'Suggested at the end of the current route';const applied=meta.beforeRef&&alreadySuggested(job.id,meta.beforeRef);return '<div class="route36-suggestion traffic"><b>🗺 Traffic-aware route suggestion</b><span>'+esc(facts.join(' · ')||'Route fit calculated from the current working route')+'</span><strong>'+esc(target)+'</strong>'+(meta.beforeRef?'<button type="button" class="route36-accept '+(applied?'applied':'')+'" data-route36-job="'+esc(job.id)+'" data-route36-before="'+esc(meta.beforeRef)+'" '+(applied?'disabled':'')+'>'+(applied?'✓ Suggested position already applied':'Accept suggested position')+'</button>':'')+'<small>Suggestion only — your drag-and-drop order remains authoritative.</small></div>'}
 if(meta.fallback)return '<div class="route36-suggestion fallback"><b>📍 Proximity match</b><span>This Satellite request was matched by local distance rather than live road traffic.</span><small>Keep your manual schedule order until a traffic-aware route is available.</small></div>';
 return '';
}
function enhanceJobs(){const jobs=new Map(DB.listJobs().map(j=>[j.id,j]));document.querySelectorAll('#main article.job').forEach(card=>{const opener=card.querySelector('[data-open]'),id=opener&&opener.dataset.open,job=id&&jobs.get(id),ev=satelliteEvent(job);let detail=card.querySelector('.route36-suggestion');if(!job||!ev){if(detail)detail.remove();return}const meta=parse(ev.label),html=suggestionMarkup(job,meta);if(!html){if(detail)detail.remove();return}const wrap=document.createElement('div');wrap.innerHTML=html;const next=wrap.firstElementChild;if(detail)detail.replaceWith(next);else{const badge=card.querySelector('.satellite35-source'),essential=card.querySelector('.job-essential34'),anchor=badge||essential||card.querySelector('.jobhead');if(anchor)anchor.insertAdjacentElement('afterend',next);else card.prepend(next)}});bindAccept()}
function bindAccept(){document.querySelectorAll('[data-route36-job]').forEach(btn=>{if(btn.dataset.route36Bound)return;btn.dataset.route36Bound='1';btn.onclick=()=>{const jobId=btn.dataset.route36Job,before=btn.dataset.route36Before,job=DB.getJob(jobId),target=DB.getJob(before);if(!job||!target||INACTIVE.has(job.status)||INACTIVE.has(target.status))return;if(LOCKED.has(job.status)){btn.textContent='Current job cannot be moved';btn.disabled=true;return}DB.setScheduleOrder(suggestedOrder(jobId,before),'satellite-route-suggestion');btn.textContent='✓ Suggested position applied';btn.classList.add('applied');btn.disabled=true;setTimeout(()=>{DB.syncRemote();schedule()},300)}})}
function enhanceLabel(){const el=document.querySelector('.brand small');if(el&&/Operations prototype/i.test(el.textContent||''))el.textContent='Operations prototype · Build 36'}
function enhance(){scheduled=false;enhanceLabel();enhanceEngine();enhanceJobs()}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance)}
async function load(){if(loading)return;loading=true;try{status=await api('/status')}catch(e){status=null}finally{loading=false;schedule()}}
const style=document.createElement('style');style.id='techBuild36Css';style.textContent=`
.route36-engine{margin:11px 0 0;padding:10px 11px;border-radius:12px;border:1px solid rgba(104,190,244,.20);background:rgba(7,27,46,.42);display:grid;gap:3px}.route36-engine b{font-size:11px;color:#bfe8ff}.route36-engine span{font-size:10px;line-height:1.35;color:#83a9c7}.route36-engine small{font-size:9px;color:#668ba8;margin-top:2px}.route36-suggestion{margin:7px 0 3px;padding:9px 10px;border-radius:11px;border:1px solid rgba(84,220,255,.34);background:linear-gradient(90deg,rgba(11,103,169,.18),rgba(7,38,64,.18));display:grid;gap:4px}.route36-suggestion.fallback{border-color:rgba(155,183,204,.25);background:rgba(60,87,108,.13)}.route36-suggestion b{font-size:10px;color:#bcecff}.route36-suggestion span{font-size:10px;color:#d9efff;line-height:1.35}.route36-suggestion strong{font-size:10px;color:#8fdcff}.route36-suggestion small{font-size:9px;color:#789db9}.route36-suggestion.fallback b{color:#b8cad8}.route36-suggestion.fallback span{color:#c8d6e1}.route36-accept{width:100%;margin-top:3px;border:1px solid rgba(83,222,255,.55);border-radius:10px;background:linear-gradient(180deg,#159be9,#0871c9);color:#fff;padding:9px;font-size:10px;font-weight:850}.route36-accept.applied{border-color:rgba(91,235,137,.50);background:linear-gradient(180deg,#21945a,#11673e);color:#dfffea}
`;document.head.appendChild(style);
DB.subscribe(schedule);DB.subscribeConnection(schedule);new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('irepair-api-change',schedule);load();setInterval(()=>{if(document.visibilityState!=='hidden')load()},60000);schedule();
})();