/* iRepair Technician · Build 42 stable controls + explicit Relay location pause/resume. */
(function(){
'use strict';
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
const TRIP_API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/trip-api';
const KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
const LIVE_KEY='irepair_live_journey_job_v1';
let availability=DB.readAvailability?DB.readAvailability():{mode:'unavailable',detourMode:'route_only',isActive:false,officeLabel:'Killay office'};
let satWatch=null,satLastPush=0,tripWatch=null,tripJob='',tripLastPush=0;
const tripStates=new Map();
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function currentView(){const x=document.querySelector('.topnav [data-nav].active');return x?x.dataset.nav:'jobs'}
function liveId(){try{return localStorage.getItem(LIVE_KEY)||''}catch(e){return ''}}
function setLiveId(id){try{id?localStorage.setItem(LIVE_KEY,id):localStorage.removeItem(LIVE_KEY)}catch(e){}}
function stopSatWatch(){if(satWatch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(satWatch);satWatch=null}
function pushSat(pos){if(!pos||!pos.coords)return;const now=Date.now();if(now-satLastPush<30000)return;satLastPush=now;DB.setAvailability({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMetres:pos.coords.accuracy}).then(v=>{availability=v;renderSatellite()})}
function syncSatWatch(){const mode=(availability&&availability.mode)||'unavailable';if(!['mobile_route','open_for_work'].includes(mode)){stopSatWatch();return}if(satWatch!==null||!navigator.geolocation)return;satWatch=navigator.geolocation.watchPosition(pushSat,()=>{}, {enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
function satCopy(){const mode=(availability&&availability.mode)||'unavailable';if(mode==='mobile_route')return 'Mobile route availability is ON. Nearby work can be matched around your route.';if(mode==='office_call_in')return 'Office call-in availability is ON for '+esc(availability.officeLabel||'Killay office')+'.';if(mode==='open_for_work')return 'Open for work is ON. The system can consider a wider local area.';return 'Satellite is off. No immediate local availability is being advertised.'}
function satHtml(){const mode=(availability&&availability.mode)||'unavailable',on=mode!=='unavailable'&&availability.isActive!==false;return '<div class="b41-head"><div><div class="b41-kicker">📡 SATELLITE AVAILABILITY</div><h3>'+(on?'Live capacity ON':'Live capacity OFF')+'</h3></div><i class="b41-dot '+(on?'on':'')+'"></i></div><p>'+satCopy()+'</p><div class="b41-modes">'+[['unavailable','Off'],['mobile_route','🚐 Mobile'],['office_call_in','🏠 Office'],['open_for_work','📡 Open']].map(x=>'<button type="button" class="'+(mode===x[0]?'active':'')+'" data-b41-mode="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>'+((mode==='mobile_route'||mode==='open_for_work')?'<div class="b41-detours">'+[['route_only','Route only'],['nearby','Nearby'],['open','Open']].map(x=>'<button type="button" class="'+((availability.detourMode||'route_only')===x[0]?'active':'')+'" data-b41-detour="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>':'')+'<small>Your precise location is used privately for route matching. Customers do not see your exact GPS pin.</small>'}
function bindSatellite(panel){panel.querySelectorAll('[data-b41-mode]').forEach(b=>b.onclick=async()=>{const mode=b.dataset.b41Mode;availability=await DB.setAvailability({mode,isActive:mode!=='unavailable',officeLabel:'Killay office'});syncSatWatch();renderSatellite()});panel.querySelectorAll('[data-b41-detour]').forEach(b=>b.onclick=async()=>{availability=await DB.setAvailability({detourMode:b.dataset.b41Detour});renderSatellite()})}
function renderSatellite(){const main=document.getElementById('main'),hero=main&&main.querySelector('.hero');let panel=document.getElementById('satellite41');if(!main||!hero||!['jobs','route'].includes(currentView())){if(panel)panel.remove();return}if(!panel){panel=document.createElement('section');panel.id='satellite41';panel.className='satellite41';hero.insertAdjacentElement('afterend',panel)}const html=satHtml();if(panel.innerHTML!==html){panel.innerHTML=html;bindSatellite(panel)}syncSatWatch()}
async function tripPost(id,payload){const r=await fetch(TRIP_API+'/jobs/'+encodeURIComponent(id),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer '+KEY,apikey:KEY},body:JSON.stringify(payload||{})});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||('Trip API '+r.status));return d}
async function postTrip(id,pos){const c=pos&&pos.coords;if(!c)throw new Error('No GPS coordinates received');return tripPost(id,{state:'en_route',locationSharingActive:true,latitude:c.latitude,longitude:c.longitude,accuracyMetres:c.accuracy,headingDegrees:Number.isFinite(c.heading)?c.heading:null})}
function setTripState(id,state,text){tripStates.set(id,{state,text:text||''});renderTripControls()}
function stopTripWatch(){if(tripWatch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(tripWatch);tripWatch=null;tripJob=''}
function tripWatchPush(id,pos){if(id!==liveId())return;const now=Date.now();if(now-tripLastPush<8000)return;tripLastPush=now;postTrip(id,pos).then(()=>setTripState(id,'live','Live GPS is updating the customer journey.')).catch(e=>setTripState(id,'error','GPS update failed: '+e.message))}
function startTripWatch(id){if(tripWatch!==null&&tripJob===id)return;stopTripWatch();if(!navigator.geolocation)return;tripJob=id;tripWatch=navigator.geolocation.watchPosition(p=>tripWatchPush(id,p),e=>setTripState(id,'error',e&&e.code===1?'Location permission is blocked for this site.':'Live GPS is temporarily unavailable.'),{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
function requestTrip(id){const job=DB.getJob(id);if(!job||job.status!=='on_my_way')return;if(!navigator.geolocation){setTripState(id,'error','Location services are unavailable in this browser.');return}setLiveId(id);setTripState(id,'requesting','Requesting iPhone location…');navigator.geolocation.getCurrentPosition(async pos=>{try{await postTrip(id,pos);setTripState(id,'live','Live GPS is updating the customer journey · accuracy about '+Math.round(pos.coords.accuracy||0)+' m.');startTripWatch(id)}catch(e){setTripState(id,'error','Location was found but could not be sent: '+e.message)}},e=>{setTripState(id,'error',e&&e.code===1?'Location permission is blocked. Allow Location for this website in Safari and try again.':e&&e.code===2?'Your iPhone could not determine its location.':'The location request timed out. Tap Try again.')},{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
async function pauseTrip(id){stopTripWatch();setLiveId('');setTripState(id,'pausing','Pausing customer location…');try{await tripPost(id,{state:'paused',locationSharingActive:false});setTripState(id,'paused','Customer location is paused. Repair Relay now shows only the last known approximate position.')}catch(e){setTripState(id,'error','Could not pause customer location: '+e.message)}}
function tripMarkup(job){const s=tripStates.get(job.id),active=liveId()===job.id;if(s&&s.state==='requesting')return '<div><b>🚐 Customer live journey</b><small>Requesting iPhone location…</small></div><button type="button" disabled>Requesting…</button>';if(s&&s.state==='pausing')return '<div><b>⏸ Customer live journey</b><small>Pausing customer location…</small></div><button type="button" disabled>Pausing…</button>';if(s&&s.state==='paused')return '<div><b>⏸ Customer location paused</b><small>'+esc(s.text)+'</small></div><button type="button" data-b42-trip="'+esc(job.id)+'">Resume live location</button>';if(s&&s.state==='live')return '<div><b>🟢 Customer live journey active</b><small>'+esc(s.text)+'</small></div><div class="trip42-actions"><button type="button" data-b42-trip="'+esc(job.id)+'">Refresh GPS</button><button type="button" class="pause" data-b42-pause="'+esc(job.id)+'">Pause location</button></div>';if(s&&s.state==='error')return '<div><b>⚠ Live location needs attention</b><small>'+esc(s.text)+'</small></div><button type="button" data-b42-trip="'+esc(job.id)+'">Try live location again</button>';return '<div><b>🚐 Customer live journey</b><small>'+(active?'This iPhone is assigned to the journey. Tap below for a fresh GPS fix.':'Location has not started on this technician device yet.')+'</small></div><button type="button" data-b42-trip="'+esc(job.id)+'">Start / Resume live location</button>'}
function renderTripControls(){const jobs=new Map(DB.listJobs().map(j=>[j.id,j]));document.querySelectorAll('#main article.job').forEach(card=>{const open=card.querySelector('[data-open]'),id=open&&open.dataset.open,job=id&&jobs.get(id);let box=card.querySelector('.trip41');if(!job||job.status!=='on_my_way'){if(box)box.remove();return}if(!box){box=document.createElement('div');box.className='trip41';const actions=card.querySelector('.actions');if(actions)actions.insertAdjacentElement('beforebegin',box);else card.appendChild(box)}const html=tripMarkup(job);if(box.innerHTML!==html)box.innerHTML=html;const start=box.querySelector('[data-b42-trip]');if(start)start.onclick=()=>requestTrip(job.id);const pause=box.querySelector('[data-b42-pause]');if(pause)pause.onclick=()=>pauseTrip(job.id)})}
function renderAll(){renderSatellite();renderTripControls()}
const style=document.createElement('style');style.textContent=`
.satellite41{margin:0 0 16px;padding:15px;border:1px solid rgba(119,207,255,.42);border-radius:19px;background:linear-gradient(145deg,rgba(12,43,71,.90),rgba(5,24,42,.86));box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 12px 30px rgba(0,0,0,.25)}.b41-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.b41-head h3{margin:3px 0 0;font-size:18px}.b41-kicker{font-size:10px;font-weight:800;letter-spacing:.06em;color:#8dc9ed}.b41-dot{width:13px;height:13px;border-radius:50%;background:#63798e}.b41-dot.on{background:#58f27f;box-shadow:0 0 14px #58f27f}.satellite41 p{font-size:11px;line-height:1.45;color:#9ec0d8}.satellite41 small{display:block;margin-top:10px;font-size:9px;line-height:1.4;color:#7194ae}.b41-modes{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.b41-modes button,.b41-detours button{border:1px solid rgba(141,196,235,.40);border-radius:12px;background:rgba(27,63,94,.62);color:#dbefff;padding:10px 5px;font-weight:700;font-size:11px}.b41-modes button.active,.b41-detours button.active{border-color:#62ddff;background:linear-gradient(180deg,rgba(25,148,247,.95),rgba(5,87,194,.96));color:#fff}.b41-detours{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px;padding-top:8px;border-top:1px solid rgba(130,190,231,.18)}.trip41{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:9px 0;padding:10px 11px;border-radius:12px;border:1px solid rgba(80,202,255,.38);background:rgba(10,74,116,.23)}.trip41 div{min-width:0}.trip41 b{display:block;font-size:10.5px;color:#d8f2ff}.trip41 small{display:block;margin-top:3px;font-size:9px;line-height:1.35;color:#8eb4cf}.trip41 button{flex:0 0 auto;border:1px solid rgba(105,222,255,.58);border-radius:10px;background:linear-gradient(180deg,#159be9,#0871c9);color:white;padding:9px 10px;font-size:9px;font-weight:850;max-width:140px}.trip41 button.pause{border-color:rgba(255,190,94,.55);background:linear-gradient(180deg,#a66a16,#78500d)}.trip41 button:disabled{opacity:.6}.trip42-actions{display:flex!important;gap:6px;flex:0 0 auto}.trip42-actions button{max-width:112px}@media(max-width:390px){.b41-modes{grid-template-columns:repeat(2,1fr)}.trip41{align-items:stretch;flex-direction:column}.trip41>button,.trip42-actions{width:100%}.trip42-actions button{flex:1;max-width:none}}
`;document.head.appendChild(style);
if(DB.subscribeAvailability)DB.subscribeAvailability(v=>{availability=v;renderSatellite()});
DB.subscribe(renderAll);DB.subscribeConnection(()=>{});
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>setTimeout(renderAll,0)));
if(DB.getAvailability)DB.getAvailability().then(v=>{availability=v;renderAll()});
renderAll();
setInterval(()=>{if(document.visibilityState!=='hidden')renderAll()},2000);
window.addEventListener('beforeunload',()=>{stopSatWatch();stopTripWatch()});
})();