/* iRepair Technician Build 34 enhancement: manual schedule, Waze and Satellite availability. */
(function(){
'use strict';
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
let availability=DB.readAvailability?DB.readAvailability():{mode:'unavailable',detourMode:'route_only',isActive:false,officeLabel:'Killay office'};
let enhancing=false,pending=false,drag=null,geoWatch=null,lastLocationPush=0,geoError='';
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const active=j=>!['completed','cancelled'].includes(j.status);
const loc=j=>[j.address,j.postcode].filter(Boolean).join(', ');
const waze=q=>'https://waze.com/ul?q='+encodeURIComponent(q)+'&navigate=yes';
function jobs(){return DB.listJobs().slice().sort((a,b)=>{const ax=active(a)?0:1,bx=active(b)?0:1;if(ax!==bx)return ax-bx;const ao=Number(a.scheduleOrder),bo=Number(b.scheduleOrder),af=a.scheduleOrder!==null&&a.scheduleOrder!==undefined&&Number.isFinite(ao),bf=b.scheduleOrder!==null&&b.scheduleOrder!==undefined&&Number.isFinite(bo);if(af&&bf&&ao!==bo)return ao-bo;if(af!==bf)return af?-1:1;const as=String(a.slot||''),bs=String(b.slot||'');if(as!==bs)return as.localeCompare(bs);return String(a.createdAt||'').localeCompare(String(b.createdAt||''))})}
function injectCss(){if(document.getElementById('techBuild34Css'))return;const s=document.createElement('style');s.id='techBuild34Css';s.textContent=`
.satellite34{margin:0 0 16px;padding:15px;border:1px solid rgba(119,207,255,.42);border-radius:19px;background:linear-gradient(145deg,rgba(12,43,71,.90),rgba(5,24,42,.86));box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 12px 30px rgba(0,0,0,.25)}
.satellite34.on{border-color:rgba(82,242,133,.58);box-shadow:inset 0 1px 0 rgba(255,255,255,.14),0 0 24px rgba(45,230,117,.12),0 12px 30px rgba(0,0,0,.25)}
.sat34-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.sat34-head h3{margin:3px 0 0;font-size:18px}.sat34-dot{width:13px;height:13px;border-radius:50%;background:#63798e;box-shadow:0 0 0 5px rgba(99,121,142,.12)}.satellite34.on .sat34-dot{background:#58f27f;box-shadow:0 0 14px #58f27f,0 0 0 5px rgba(88,242,127,.10)}
.sat34-copy{margin:10px 0 12px;line-height:1.45}.sat34-modes{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.sat34-mode,.sat34-detours button{border:1px solid rgba(141,196,235,.40);border-radius:12px;background:rgba(27,63,94,.62);color:#dbefff;padding:10px 5px;font-weight:700;font-size:11px}.sat34-mode.active,.sat34-detours button.active{border-color:#62ddff;background:linear-gradient(180deg,rgba(25,148,247,.95),rgba(5,87,194,.96));color:#fff;box-shadow:0 0 12px rgba(70,202,255,.30)}.sat34-sub{margin-top:12px;padding-top:11px;border-top:1px solid rgba(130,190,231,.18)}.sat34-sub>span{display:block;margin-bottom:7px;color:#8fb8d8;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.sat34-detours{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.sat34-privacy{margin-top:11px;color:#7698b4;font-size:10.5px;line-height:1.35}
.reorder34-help{margin:-2px 0 10px;padding:9px 11px;border-radius:12px;background:rgba(63,137,190,.12);border:1px solid rgba(102,181,236,.18);color:#9fc5e3;font-size:11px}.job.reorder34{position:relative;transition:transform .16s ease,opacity .16s ease,box-shadow .16s ease;touch-action:pan-y}.job.reorder34.dragging34{z-index:999;opacity:.94;transform:scale(1.018);box-shadow:0 18px 42px rgba(0,0,0,.48),0 0 0 2px rgba(85,223,255,.62)!important;touch-action:none}.job.dragtarget34{transform:translateY(2px)}
.schedule34-bar{display:flex;align-items:center;gap:8px;margin:0 0 9px}.schedule34-num{display:flex;width:28px;height:28px;border-radius:50%;align-items:center;justify-content:center;background:linear-gradient(180deg,#1894ff,#075dc4);color:#fff;font-size:12px;font-weight:850;box-shadow:0 0 10px rgba(45,166,255,.35)}.schedule34-grip{color:#7ea8c8;font-size:19px;line-height:24px;letter-spacing:-7px;padding-right:5px;user-select:none}.schedule34-label{color:#8fb8d8;font-size:10.5px;font-weight:750;text-transform:uppercase;letter-spacing:.04em}
.job-essential34{display:grid;grid-template-columns:1fr;gap:7px;margin:10px 0;padding:11px;border-radius:13px;background:rgba(5,24,42,.48);border:1px solid rgba(119,183,226,.16)}.job-essential34 div{display:grid;grid-template-columns:72px 1fr;gap:8px;align-items:start}.job-essential34 span{color:#7399b9;font-size:10px;font-weight:750;text-transform:uppercase;letter-spacing:.04em}.job-essential34 b{font-size:12.5px;line-height:1.35;color:#e6f3ff}.waze34{text-decoration:none!important;display:inline-flex!important;align-items:center;justify-content:center}
body.dragging34{overscroll-behavior:none;-webkit-user-select:none;user-select:none}
@media(max-width:390px){.sat34-modes{grid-template-columns:repeat(2,1fr)}.job-essential34 div{grid-template-columns:64px 1fr}}
`;document.head.appendChild(s)}
function currentView(){const a=document.querySelector('.topnav [data-nav].active');return a?a.dataset.nav:'jobs'}
function satMarkup(){const a=availability||{},mode=a.mode||'unavailable',isOn=mode!=='unavailable'&&a.isActive!==false;let msg='Satellite is off. No immediate local availability is being advertised.';if(mode==='office_call_in')msg='Office call-in availability is ON for '+esc(a.officeLabel||'Killay office')+'.';if(mode==='mobile_route')msg='Mobile route availability is ON. Nearby work can be matched around your route.';if(mode==='open_for_work')msg='Open for work is ON. The system can consider a wider local area.';if(mode==='mobile_route'||mode==='open_for_work')msg+=' '+(geoError?esc(geoError):(a.locationFresh?'Live location linked.':'Waiting for live location…'));return '<div class="sat34-head"><div><div class="eyebrow">📡 SATELLITE AVAILABILITY</div><h3>'+(isOn?'Live capacity ON':'Live capacity OFF')+'</h3></div><span class="sat34-dot"></span></div><div class="muted sat34-copy">'+msg+'</div><div class="sat34-modes">'+[['unavailable','Off'],['mobile_route','🚐 Mobile'],['office_call_in','🏠 Office'],['open_for_work','📡 Open']].map(x=>'<button class="sat34-mode '+(mode===x[0]?'active':'')+'" data-sat34-mode="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>'+((mode==='mobile_route'||mode==='open_for_work')?'<div class="sat34-sub"><span>Detour preference</span><div class="sat34-detours">'+[['route_only','Route only'],['nearby','Nearby'],['open','Open']].map(x=>'<button class="'+((a.detourMode||'route_only')===x[0]?'active':'')+'" data-sat34-detour="'+x[0]+'">'+x[1]+'</button>').join('')+'</div></div>':'')+'<div class="sat34-privacy">Your exact live pin is retained for route matching. Prospective customers only see that a technician is available in their area.</div>'}
function ensureSatellite(){const v=currentView(),main=document.getElementById('main'),hero=main&&main.querySelector('.hero');let panel=document.getElementById('satellite34');if(v!=='jobs'&&v!=='route'){if(panel)panel.remove();return}if(!main||!hero)return;if(!panel){panel=document.createElement('section');panel.id='satellite34';panel.className='satellite34';hero.insertAdjacentElement('afterend',panel)}const mode=(availability&&availability.mode)||'unavailable';panel.classList.toggle('on',mode!=='unavailable'&&availability.isActive!==false);panel.innerHTML=satMarkup();panel.querySelectorAll('[data-sat34-mode]').forEach(b=>b.onclick=()=>{const mode=b.dataset.sat34Mode;DB.setAvailability({mode,isActive:mode!=='unavailable',officeLabel:'Killay office'}).then(v=>{availability=v;scheduleEnhance()})});panel.querySelectorAll('[data-sat34-detour]').forEach(b=>b.onclick=()=>DB.setAvailability({detourMode:b.dataset.sat34Detour}).then(v=>{availability=v;scheduleEnhance()}))}
function enhanceWaze(root){root.querySelectorAll('a[href^="https://maps.apple.com/"]').forEach(a=>{let q='';try{q=new URL(a.href).searchParams.get('q')||''}catch(e){}if(q){a.href=waze(q);a.textContent=a.closest('.route')?'📍 Open in Waze →':'📍 Waze';a.classList.add('waze34');a.target='_blank';a.rel='noopener'}})}
function positionMap(){return new Map(jobs().filter(active).map((j,i)=>[j.id,i+1]))}
function enhanceJobs(){if(currentView()!=='jobs')return;const main=document.getElementById('main');if(!main)return;const cards=[...main.querySelectorAll(':scope > article.job')],byId=new Map(jobs().map(j=>[j.id,j])),pos=positionMap();if(!cards.length)return;cards.forEach(card=>{const open=card.querySelector('[data-open]'),id=open&&open.dataset.open,j=id&&byId.get(id);if(!j)return;card.dataset.job34=id;if(active(j)){card.classList.add('reorder34');if(!card.querySelector('.schedule34-bar')){const bar=document.createElement('div');bar.className='schedule34-bar';bar.innerHTML='<span class="schedule34-num">'+(pos.get(id)||'—')+'</span><span class="schedule34-grip">⋮⋮</span><span class="schedule34-label">Drag to reorder today’s schedule</span>';card.prepend(bar)}else{const n=card.querySelector('.schedule34-num');if(n)n.textContent=String(pos.get(id)||'—')}}const address=loc(j);let essential=card.querySelector('.job-essential34');if(!essential){essential=document.createElement('div');essential.className='job-essential34';const head=card.querySelector('.jobhead');if(head)head.insertAdjacentElement('afterend',essential);else card.prepend(essential)}essential.innerHTML='<div><span>Customer</span><b>'+esc(j.customerName)+'</b></div><div><span>Repair</span><b>'+esc(j.repair)+'</b></div><div><span>Address</span><b>'+esc(address||'Address not set')+'</b></div>';if(address){const actions=card.querySelector('.actions');if(actions&&!actions.querySelector('.waze34-card')){const a=document.createElement('a');a.className='btn secondary waze34 waze34-card';a.href=waze(address);a.target='_blank';a.rel='noopener';a.textContent='📍 Waze';actions.prepend(a)}}});const ordered=jobs(),cardById=new Map(cards.map(c=>[c.dataset.job34,c]));ordered.forEach(j=>{const c=cardById.get(j.id);if(c&&c.parentNode===main)main.appendChild(c)});let help=document.getElementById('reorder34Help');if(!help){help=document.createElement('div');help.id='reorder34Help';help.className='reorder34-help';help.textContent='Press and hold a complete job card, then drag it up or down to change the running order. Your order is saved to iRepair Core.';const first=main.querySelector('article.job');if(first)first.insertAdjacentElement('beforebegin',help)}bindDrag()}
function renumberDom(){document.querySelectorAll('#main > article.job.reorder34').forEach((c,i)=>{const n=c.querySelector('.schedule34-num');if(n)n.textContent=String(i+1)})}
function saveDomOrder(){const ids=[...document.querySelectorAll('#main > article.job.reorder34[data-job34]')].map(c=>c.dataset.job34);if(ids.length&&DB.setScheduleOrder)DB.setScheduleOrder(ids,'technician-drag')}
function finishDrag(save){if(!drag)return;clearTimeout(drag.timer);const card=drag.card,was=drag.active;if(card){card.classList.remove('dragging34');if(card.releasePointerCapture&&drag.pointerId!=null){try{card.releasePointerCapture(drag.pointerId)}catch(e){}}}document.body.classList.remove('dragging34');document.querySelectorAll('.dragtarget34').forEach(x=>x.classList.remove('dragtarget34'));drag=null;if(was&&save){saveDomOrder();scheduleEnhance()}}
function bindDrag(){document.querySelectorAll('#main > article.job.reorder34').forEach(card=>{if(card.dataset.drag34Bound)return;card.dataset.drag34Bound='1';card.addEventListener('pointerdown',e=>{if(e.button!=null&&e.button!==0)return;if(e.target.closest('button,a,input,textarea,select,label,.detail'))return;drag={card,pointerId:e.pointerId,startY:e.clientY,active:false,timer:setTimeout(()=>{if(!drag||drag.card!==card)return;drag.active=true;card.classList.add('dragging34');document.body.classList.add('dragging34');try{card.setPointerCapture(e.pointerId)}catch(err){}},180)};});card.addEventListener('pointermove',e=>{if(!drag||drag.card!==card)return;if(!drag.active){if(Math.abs(e.clientY-drag.startY)>9){clearTimeout(drag.timer);drag=null}return}e.preventDefault();const cards=[...document.querySelectorAll('#main > article.job.reorder34')].filter(c=>c!==card);let target=null;for(const c of cards){const r=c.getBoundingClientRect();if(e.clientY<r.top+r.height/2){target=c;break}}const parent=card.parentNode;if(!parent)return;if(target){target.classList.add('dragtarget34');parent.insertBefore(card,target)}else{const last=cards[cards.length-1];if(last)parent.insertBefore(card,last.nextSibling)}document.querySelectorAll('.dragtarget34').forEach(x=>{if(x!==target)x.classList.remove('dragtarget34')});renumberDom()});card.addEventListener('pointerup',()=>finishDrag(true));card.addEventListener('pointercancel',()=>finishDrag(false))})}
function enhanceRoute(){if(currentView()!=='route')return;const main=document.getElementById('main');if(main)enhanceWaze(main)}
function enhanceAll(){if(enhancing||drag&&drag.active)return;enhancing=true;try{injectCss();ensureSatellite();enhanceJobs();enhanceRoute();const main=document.getElementById('main');if(main)enhanceWaze(main);syncGeo()}finally{enhancing=false}}
function scheduleEnhance(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;enhanceAll()})}
function pushLocation(pos){if(!pos||!pos.coords)return;const now=Date.now();if(now-lastLocationPush<30000)return;lastLocationPush=now;geoError='';DB.setAvailability({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMetres:pos.coords.accuracy}).then(v=>{availability=v;scheduleEnhance()})}
function startGeo(){if(geoWatch!==null)return;if(!navigator.geolocation){geoError='Location services are unavailable in this browser.';scheduleEnhance();return}geoWatch=navigator.geolocation.watchPosition(pushLocation,err=>{geoError=err&&err.code===1?'Location permission is off — enable it for live nearby-work matching.':'Live location temporarily unavailable.';scheduleEnhance()},{enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
function stopGeo(){if(geoWatch!==null&&navigator.geolocation){navigator.geolocation.clearWatch(geoWatch);geoWatch=null}geoError=''}
function syncGeo(){const m=(availability&&availability.mode)||'unavailable';if(m==='mobile_route'||m==='open_for_work')startGeo();else stopGeo()}
function start(){injectCss();const main=document.getElementById('main');if(main)new MutationObserver(scheduleEnhance).observe(main,{childList:true,subtree:true});document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>setTimeout(scheduleEnhance,0)));if(DB.subscribeAvailability)DB.subscribeAvailability(v=>{availability=v;scheduleEnhance()});if(DB.getAvailability)DB.getAvailability().then(v=>{availability=v;scheduleEnhance()});scheduleEnhance()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.addEventListener('beforeunload',stopGeo);
})();