/* iRepair Technician · Build 36 route-intelligence feedback. */
(function(){
'use strict';
if(!window.IRepairDB)return;
const DB=window.IRepairDB;
const API='https://psswyljihufyxiieqziu.supabase.co/functions/v1/satellite-api';
const API_KEY='sb_publishable_oRtVKV3yejg4521iPjNeDg_YWxa088L';
let status=null,scheduled=false,loading=false;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/json',Authorization:'Bearer '+API_KEY,apikey:API_KEY}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
function sourceEvent(job){return (job&&job.timeline||[]).slice().reverse().find(e=>e&&e.type==='satellite')||null}
function parse(label){const s=String(label||''),extra=s.match(/\+(\d+) min detour/i),drive=s.match(/(\d+) min drive to customer/i),before=s.match(/suggested before ([A-Z0-9-]+)/i);return{traffic:/traffic-aware route/i.test(s),fallback:/proximity fallback/i.test(s),extra:extra?Number(extra[1]):null,drive:drive?Number(drive[1]):null,before:before?before[1]:''}}
function engineText(){const r=status&&status.routing||status&&status.satellite&&status.satellite.routing||{};if(r.provider==='google_routes')return '<b>🧭 Traffic-aware route matching active</b><span>Live road travel and detour scoring are available for Satellite matching.</span>';return '<b>🧭 Route engine ready</b><span>Satellite is using proximity matching until the Google traffic-routing credential is connected.</span>'}
function profileText(){const s=status&&status.satellite||{},m=s.detourMode||'route_only',labels={route_only:'Route only · up to 8 min extra driving',nearby:'Nearby · up to 15 min extra driving',open:'Open · up to 30 min extra driving'};return labels[m]||labels.route_only}
function setHtml(el,html){if(el&&el.innerHTML!==html)el.innerHTML=html}
function enhanceEngine(){const panel=document.getElementById('satellite34');if(!panel)return;let box=panel.querySelector('.route36-engine');if(!box){box=document.createElement('div');box.className='route36-engine';const privacy=panel.querySelector('.sat34-privacy');if(privacy)privacy.insertAdjacentElement('beforebegin',box);else panel.appendChild(box)}setHtml(box,engineText()+'<small>'+esc(profileText())+'</small>')}
function enhanceJobs(){const jobs=new Map(DB.listJobs().map(j=>[j.id,j]));document.querySelectorAll('#main article.job').forEach(card=>{const opener=card.querySelector('[data-open]'),id=opener&&opener.dataset.open,job=id&&jobs.get(id),ev=sourceEvent(job);let detail=card.querySelector('.route36-suggestion');if(!ev){if(detail)detail.remove();return}const p=parse(ev.label);if(!p.traffic&&!p.fallback){if(detail)detail.remove();return}if(!detail){detail=document.createElement('div');detail.className='route36-suggestion';const badge=card.querySelector('.satellite35-source');if(badge)badge.insertAdjacentElement('afterend',detail);else{const essential=card.querySelector('.job-essential34');if(essential)essential.insertAdjacentElement('beforebegin',detail);else card.prepend(detail)}}let html='';if(p.traffic){const bits=[];if(p.drive!=null)bits.push(p.drive+' min to customer');if(p.extra!=null)bits.push('+'+p.extra+' min extra driving');if(p.before)bits.push('suggested before '+p.before);detail.classList.remove('fallback');html='<b>🗺 Route suggestion</b><span>'+esc(bits.join(' · ')||'Traffic-aware Satellite route match')+'</span><small>Suggestion only — drag the complete job card anywhere you prefer.</small>'}else{detail.classList.add('fallback');html='<b>📍 Proximity suggestion</b><span>This Satellite request was matched by local distance rather than live road traffic.</span><small>Your manual schedule order remains authoritative.</small>'}setHtml(detail,html)})}
function enhanceBuildLabel(){const el=document.querySelector('.brand small');if(el&&/Operations prototype/i.test(el.textContent||'')&&el.textContent!=='Operations prototype · Build 36')el.textContent='Operations prototype · Build 36'}
function enhance(){scheduled=false;enhanceBuildLabel();enhanceEngine();enhanceJobs()}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance)}
async function load(){if(loading)return;loading=true;try{status=await api('/status')}catch(e){status=null}finally{loading=false;schedule()}}
const style=document.createElement('style');style.id='techBuild36Css';style.textContent=`
.route36-engine{margin:11px 0 0;padding:10px 11px;border-radius:12px;border:1px solid rgba(104,190,244,.20);background:rgba(7,27,46,.42);display:grid;gap:3px}.route36-engine b{font-size:11px;color:#bfe8ff}.route36-engine span{font-size:10px;line-height:1.35;color:#83a9c7}.route36-engine small{font-size:9px;color:#668ba8;margin-top:2px}.route36-suggestion{margin:7px 0 3px;padding:9px 10px;border-radius:11px;border:1px solid rgba(84,220,255,.34);background:linear-gradient(90deg,rgba(11,103,169,.18),rgba(7,38,64,.18));display:grid;gap:3px}.route36-suggestion.fallback{border-color:rgba(155,183,204,.25);background:rgba(60,87,108,.13)}.route36-suggestion b{font-size:10px;color:#bcecff}.route36-suggestion span{font-size:10px;color:#d9efff;line-height:1.35}.route36-suggestion small{font-size:9px;color:#789db9}.route36-suggestion.fallback b{color:#b8cad8}.route36-suggestion.fallback span{color:#c8d6e1}
`;document.head.appendChild(style);
DB.subscribe(schedule);DB.subscribeConnection(schedule);new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('irepair-api-change',schedule);load();setInterval(()=>{if(document.visibilityState!=='hidden')load()},60000);schedule();
})();